src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_in_Lacs_Max__c</fullName>
        <label>Budget in Lacs (Max)</label>
        <summarizedField>Opportunity.S_Budget_In_lacs__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Budget_in_Lacs_Min__c</fullName>
        <label>Budget in Lacs (Min)</label>
        <summarizedField>Opportunity.S_Budget_In_lacs__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S_Cross_Project_Exposure__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cross Project Exposure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_PReason_for_Purchase__c</fullName>
        <label>Reason For Purchase</label>
        <picklist>
            <picklistValues>
                <fullName>End use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>S_Possession_Type__c</fullName>
        <label>Possession Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ready To Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Up to 6 Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 to 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 to 2 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 to 5 Years</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>S_Pr_History__c</fullName>
        <label>Product History</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>S_Type_of_accomadation__c</fullName>
        <label>Type Of Accomodation</label>
        <picklist>
            <picklistValues>
                <fullName>1 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.5 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penthouse</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Possession_Requirement__c</fullName>
        <label>Possession Requirement</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Live In (RTLI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Move in (RTMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 1 to 2 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 2 to 3 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – More than 3 years)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose of Purchase</label>
        <picklist>
            <picklistValues>
                <fullName>Capital Gain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second home</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>S_Budget_In_lacs__c</fullName>
        <label>Budget (In lacs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOpportunityManagementServices.cls
@isTest
private  Class TestOpportunityManagementServices 
{
  @isTest  
  static void SLBMTest() 
  {
        Project__c p = TestDataFactory.createProject('ONE', '111');
        Project__c p1 = TestDataFactory.createProject('TWO', '222');
        
        Account acc = TestDataFactory.createPATemplate('TestPA1' , 'testleada@xanadutest.com', '9876544441', false);
        
        List<Opportunity>  oList = TestDataFactory.createOpptyForAccountCross(acc.Id, p.Id, 3);
                        
        Test.startTest();
          
          List<Account> ua = [Select Id,S_Type_of_accomadation__c,S_PReason_for_Purchase__c,S_Possession_Type__c, S_Pr_History__c, S_Cross_Project_Exposure__c,Budget_in_Lacs_Max__c, Budget_in_Lacs_Min__c from Account where Id = :acc.Id]; //
         /* System.assertEquals(5000000,ua[0].Budget_in_Lacs_Max__c);
          System.assertEquals(5000000,ua[0].Budget_in_Lacs_Min__c);
          System.assertEquals('ONE',ua[0].S_Pr_History__c);
          System.assertEquals(3, ua[0].S_Cross_Project_Exposure__c);
          System.assertEquals('Capital Gain',ua[0].S_PReason_for_Purchase__c);
          System.assertEquals('Ready to Live In (RTLI)',ua[0].S_Possession_Type__c);*/
          
          
          oList[1].Project__c = p1.Id;
          oList[1].S_Budget_In_lacs__c = 2000;
          oList[2].S_Budget_In_lacs__c = 50000000;
          oList[2].Possession_Requirement__c = 'Under Construction (UC – 1 to 2 years)';
          oList[2].Purpose__c = 'Gift';
          
          update oList;
          
         List<Account> ua1 = [Select Id,S_Type_of_accomadation__c,S_PReason_for_Purchase__c,S_Possession_Type__c,Budget_in_Lacs_Max__c, Budget_in_Lacs_Min__c, S_Pr_History__c,S_Cross_Project_Exposure__c from Account where Id = :acc.Id];  //
          
         /* System.assertEquals(50000000,ua1[0].Budget_in_Lacs_Max__c);
          System.assertEquals(2000,ua1[0].Budget_in_Lacs_Min__c);
          System.assertEquals('ONE,TWO',ua1[0].S_Pr_History__c);
          System.assertEquals(3, ua1[0].S_Cross_Project_Exposure__c);
          System.assertEquals('Capital Gain,Gift',ua1[0].S_PReason_for_Purchase__c);
          System.assertEquals('Ready to Live In (RTLI),Under Construction (UC – 1 to 2 years)',ua1[0].S_Possession_Type__c);
                    */
        Test.stopTest();
 
  }
}