src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Name__c</fullName>
        <label>Primary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Project field is blank or Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_Dishonour__c</fullName>
        <label>Cheque Dishonour</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Rs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount (Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Drawee Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Banking__c</fullName>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Payment Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed - Insufficient Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed – Signature mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed – PDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed – Stop payment by client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed – Overwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Failed – Amount Mismatch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cheque_DD_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_DD__c</fullName>
        <label>Cheque/DD No.</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DraweeBank__c</fullName>
        <label>Drawee Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Abhyudaya Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad Mercantile Co-Op Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Janata Commercial Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Urban Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allahabad Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andaman and Nicobar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh Mahesh Co-Op Urban Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh State Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axis Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Baroda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bassein Catholic Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank (Mumbai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharati Sahakari Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bombay Mercantile Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canara Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catholic Syrian Bank Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh Rajya Sahakari Bank Maryadit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citizen Credit Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmos Co-operative Urban Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Drawn_in_favour_of__c</fullName>
        <label>Drawn in favour of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD/Pay Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Project__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Block, CRM Returned To Sales, Hold, Sold, Vacant, Welcome Call Pending, BIP - Sales, BIP - RM Verification, BIP - CRM, BIP</value>
            </filterItems>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Project_Unit__c.Project__c</valueField>
            </filterItems>
            <infoMessage>Block, CRM Returned To Sales, Vacant, Welcome Call Pending, BIP - Sales, BIP - RM Verification, Sold, Block</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Reject__c</fullName>
        <label>Reason for Receipt Rejection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_rejection_new__c</fullName>
        <label>Physical Verification Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Over writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Date lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Wrong Favoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Amount mismatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Signature missing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected-Old Cheque Format CTS2010</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Receipt_Status__c</fullName>
        <label>Receipt Status</label>
        <picklist>
            <picklistValues>
                <fullName>UnProcessed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Finance Submission Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Sent for Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishonored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Verification Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/showReceiptDetails.cls
public class showReceiptDetails
{
    public Id receiptId {get;set;}
    public String reasonForRejection {get;set;}
    public Receipt__c rd {get;set;}
    public string paymentTowards {get;set;}
    public string bankAccount {get;set;}
    public Boolean letterH { get; set; }
    public String CustomerPrimaryName {
        get;
        set;
    }
    public String CustomerOtherApplicantName {
        get;
        set;
    }
    public String CustomerMailingAddress {
        get;
        set;
    }
    public List<Receipt__c> receiptList {
    	get;
    	set;
    }
     public String CustomerMobilePhone {
        get;
        set;
    }

    public void getReceiptDetails()
    {
    	bankAccount = '';
    	paymentTowards = '';
         receiptList = new List<Receipt__c>(); 
         rd = new Receipt__c();
         system.debug('Inside getReceiptDetails Method');
         system.debug('Receipt Id : '+receiptId);
         
		         receiptList = [SELECT id, Name,Mode__c,
		         Bank__c,Project__c,Project__r.Name,
		         Project_Unit__c,Project_Unit__r.Name,
		         Cheque_DD__c,Opportunity__c,
		         Opportunity__r.Name,Cheque_DD_Date__c,
		         Amount_Rs__c,
		         Reason_for_Reject__c,
		         Drawn_in_favour_of__c,
		         Banking__c,
		         DraweeBank__c,
		         Reason_for_rejection_new__c,
		         receipt_status__c,
		         Project__r.Cheque_Dishonour__c,
		         Opportunity__r.Primary_Name__c,
		         Opportunity__r.Primary_Phone__c,
		         Opportunity__r.Other_Applicants_Name__c,
		         Opportunity__r.Mailing_Address__C,
		         Project__r.Project_Image__c,
		         Project__r.Footer_Image__c,
		         Receipt_Date__c
		         FROM Receipt__c WHERE id = :receiptId];
		         
		         if(receiptList != null && receiptList.size() == 1) {
		         	if(string.IsNotBlank(receiptList[0].receipt_status__c)  && receiptList[0].receipt_status__c.equalsIgnoreCase('Physical Verification Rejected'))
		         		reasonForRejection = receiptList[0].Reason_for_rejection_new__c;
		         	else if (string.IsNotBlank(receiptList[0].receipt_status__c)  && receiptList[0].receipt_status__c.equalsIgnoreCase('Dishonored'))
		       			reasonForRejection = receiptList[0].Banking__c;
		       		if(string.IsNotBlank(receiptList[0].Drawn_in_favour_of__c)) {
		       			List<String> sList = receiptList[0].Drawn_in_favour_of__c.split('\\|', 5); 
		       			system.debug(sList);
		       			if(sList != null && sList.size() > 0) {
		       				paymentTowards = sList[0];
		       			}
		       			Integer count = 0;
		       			for(String s: sList) {
		       				if(count != 0) {
		       					bankAccount += sList[count] + ',';
		       				}
		       				count ++;
		       			}
		       			// remove the last character only if its a comma.
						if(bankAccount.length() > 0 && bankAccount.substring(bankAccount.length() -1).equals(','))
							bankAccount = bankAccount.substring(0,bankAccount.length() -1);
		       			system.debug('bank account:' + bankAccount);
		       			system.debug('payment towards:' + paymentTowards);
		       			
		       			CustomerPrimaryName  = receiptList[0].Opportunity__r.Primary_Name__c;
                    	CustomerOtherApplicantName = receiptList[0].Opportunity__r.Other_Applicants_Name__c;
                    	CustomerMailingAddress = receiptList[0].Opportunity__r.Mailing_Address__c;
                    	CustomerMobilePhone  =  receiptList[0].Opportunity__r.Primary_Phone__c;
		       		}
		       		
		       		
		         }
         if(receiptList != null && receiptList.size() ==1) {
         	rd= receiptList[0];
         }
    }
}