src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <picklist>
            <picklistValues>
                <fullName>Salaried</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housewife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zones__c</fullName>
        <label>Zone (O)</label>
        <picklist>
            <controllingField>Suburb_O__c</controllingField>
            <picklistValues>
                <fullName>NAVI MUMBAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH CENTRAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EASTERN SUBURBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CENTRAL SUBURBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH MUMBAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THANE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN SUBURBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAR WESTERN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAR EASTERN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN MUMB - BKC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN MUMBAI - MAIN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Budget_In_lacs__c</fullName>
        <label>Budget (In lacs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <picklist>
            <picklistValues>
                <fullName>Salaried</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housewife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Possession_Requirement__c</fullName>
        <label>Possession Requirement</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Move in (RTMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Live In (RTLI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 1 to 2 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 2 to 3 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – More than 3 years)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Alternate_Email_Id__c</fullName>
        <label>Alternate Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>RDS_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zones__c</fullName>
        <label>Zone (O)</label>
        <picklist>
            <picklistValues>
                <fullName>THANE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN SUBURBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAR WESTERN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAR EASTERN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN MUM - BKC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WESTERN MUMBAI - MAIN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Blair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amalapuram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anakapalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bapatla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bheemunipatnam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhimavaram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bobbili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chilakaluripet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuddapah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharmavaram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eluru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gooty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudivada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guntakal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guntur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hanamkonda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindupur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaggaiahpet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammalamadugu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kadapa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kadiri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kakinada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandukur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kavali</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <picklist>
            <picklistValues>
                <fullName>Salaried Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Promoters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housewife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Possession_Requirement__c</fullName>
        <label>Possession Requirement</label>
        <picklist>
            <picklistValues>
                <fullName>Ready to Live In (RTLI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Move in (RTMI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 1 to 2 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – 2 to 3 years)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction (UC – More than 3 years)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site_Visit__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name1__c</fullName>
        <label>Customer Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_No2__c</fullName>
        <label>Mobile No</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source1__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perimeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exhibition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corprate Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Walk-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hoardings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of Mouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door to Door Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outstation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Television Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database calling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mailers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loyalty &amp; Referral Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewSiteVisitControllerTest.cls
@isTest
 public class NewSiteVisitControllerTest
 {
     @isTest
         private static void WalkInSearchPageTest() { 
             project__c p = createProject();
             Account a = createPAAccount();
             Opportunity o = createOpp(a.Id,p.Id);
             
             test.startTest();
                 pageReference pageRef = page.Site_Visit_Search_Page;
                 Test.setCurrentPage(pageRef);
                 SVsearch walkInSearch = new SVsearch ();
                 walkInSearch.strProjectId = p.Id;
                 walkInSearch.NewLead.MobilePhone= '1212121213';
                 walkInSearch.NewLead.lastName = 'testlead';
                 walkInSearch.NewLead.Email = 'testlead@test.in';
                 walkInSearch.NewLead.RDS_Alternate_Email_Id__c = 'testlead1@test.in'; 
                 walkInSearch.OpportunityId = o.Id;
                 walkInSearch.saveMethod();
                 walkInSearch.searchAllLead();
                 
                 SVsearch walkInSearch1 = new SVsearch ();
                 
                 walkInSearch1.strProjectId = p.Id; 
                 walkInSearch1.NewLead.MobilePhone= '1212121212';
                 walkInSearch1.saveMethod();
                 walkInSearch1.searchAllLead();
               
                 SVsearch walkInSearch11= new SVsearch ();
                
                
             Lead leadObj=new Lead();
             leadObj.LastName='Test Lead';
             leadObj.MobilePhone='9860708789';
             leadObj.Email='test@stetig.in';
             leadObj.RDS_Alternate_Email_Id__c='test1@stetig.in';
             leadObj.RDS_Project__c =p.Id;
             leadObj.Budget_In_lacs__c=100; 
             insert leadObj;
             
                 walkInSearch11.strProjectId = p.Id;
                 
                 walkInSearch11.NewLead = leadObj;
                 walkInSearch11.saveMethod();
                 walkInSearch11.searchAllLead();
                 walkInSearch11.goBack();
                 
             test.stopTest();
         }
         @isTest
         private static void walkInMainformserachpageTest() {
             project__c p = createProject();
             //Lead l = createleadTemplate1();
             Lead leadObj=new Lead();
             leadObj.LastName='Test Lead';
             leadObj.MobilePhone='9860708788';
             leadObj.Email ='test@test.stetig';
             leadObj.RDS_Project__c =p.Id;
             leadObj.Budget_In_lacs__c=100; 
             leadObj.Zones__c ='test';
             leadObj.Possession_Requirement__c = 'test';
             insert leadObj;
             
             
             
             
              NewSiteVisitController walkInForm10 = new NewSiteVisitController();
                 walkInForm10.strLeadId=leadObj.Id;
                   
             Account a = createPAAccount();
             
             Opportunity o = createOpp(a.Id,p.Id);
             walkInForm10.strOptyId=o.Id;
             walkInForm10.strAccountId=a.Id;
             test.startTest();
                 pageReference pageRef = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef);
                 ApexPages.currentPage().getParameters().put('Leadid',leadObj.id);
                 ApexPages.currentPage().getParameters().put('projectId',p.Id);
                
                 NewSiteVisitController walkInForm = new NewSiteVisitController();
                 pageReference pageRef1 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef1);
                 
                 ApexPages.currentPage().getParameters().put('optyid',o.Id);
                 
                 ApexPages.currentPage().getParameters().put('projectId',p.Id);
                 NewSiteVisitController walkInForm1 = new NewSiteVisitController();
                 
                 pageReference pageRef11 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef11);
                 ApexPages.currentPage().getParameters().put('Accid',a.Id);
                 ApexPages.currentPage().getParameters().put('projectId',p.Id);
                 NewSiteVisitController walkInForm11 = new NewSiteVisitController();
                 
                
                pageReference pageRef22 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef22);
                 
                 ApexPages.currentPage().getParameters().put('mobile','1111122222');
                 NewSiteVisitController walkInForm22 = new NewSiteVisitController();
              
                 pageReference pageRef33 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef33);
                 
                  ApexPages.currentPage().getParameters().put('mobile','2222233333');                 
                  NewSiteVisitController walkInForm33 = new NewSiteVisitController();
                  walkInForm33.sv.Customer_Name1__c='Mr. Aditya Marne';
                  walkInForm33.sv.Mobile_No2__c = '1234567890';
                  walkInForm33.sv.Email2__c = 'test@testing.in';
                  walkInForm33.sv.Source1__c = 'Others';
                  walkInForm33.sv.City__c = 'Pune';
                  walkInForm33.sv.Occupation__c='CA';
                  walkInForm33.sv.Sub_Source2__c ='Exhibition';
                  walkInForm33.save();
                  
                 pageReference pageRef44 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef44);
                 
                  ApexPages.currentPage().getParameters().put('Leadid',LeadObj.Id);                 
                  NewSiteVisitController walkInForm44 = new NewSiteVisitController();
                  walkInForm44.sv.Customer_Name1__c='Mr. Aditya Marne';
                  walkInForm44.sv.Mobile_No2__c = '1234567890';
                  walkInForm44.sv.Email2__c = 'test@testing.in';
                  walkInForm44.sv.Source1__c = 'Others';
                  walkInForm44.sv.City__c = 'Pune';
                  walkInForm44.sv.Occupation__c='CA';
                  walkInForm44.sv.Sub_Source2__c ='Exhibition';
                  walkInForm44.save();
                  
                 
                  
                  
                  pageReference pageRef55 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef55);
                 
                  ApexPages.currentPage().getParameters().put('Optyid',o.Id);                 
                  NewSiteVisitController walkInForm55 = new NewSiteVisitController();
                  walkInForm55.sv.Customer_Name1__c='Mr. Aditya Marne';
                  walkInForm55.sv.Mobile_No2__c = '1234567890';
                  walkInForm55.sv.Email2__c = 'test@testing.in';
                  walkInForm55.sv.Source1__c = 'Others';
                  walkInForm55.sv.City__c = 'Pune';
                  walkInForm55.sv.Occupation__c='CA';
                  walkInForm55.sv.Sub_Source2__c ='Exhibition';
                  walkInForm55.strRecordTypeId = Schema.SObjectType.Site_Visit__c.getRecordTypeInfosByName().get('Site Visit Form').getRecordTypeId();
                  
                  walkInForm55.save();
                  
                  pageReference pageRef66 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef66);
                 
                  ApexPages.currentPage().getParameters().put('Accid',a.Id);                 
                  NewSiteVisitController walkInForm66 = new NewSiteVisitController();
                  walkInForm66.sv.Customer_Name1__c='Mr. Aditya Marne';
                  walkInForm66.sv.Mobile_No2__c = '1234567890';
                  walkInForm66.sv.Email2__c = 'test@testing.in';
                  walkInForm66.sv.Source1__c = 'Others';
                  walkInForm66.sv.City__c = 'Pune';
                  walkInForm66.sv.Occupation__c='CA';
                  walkInForm66.sv.Sub_Source2__c ='Exhibition';
                  walkInForm66.save();
              
              test.stopTest();  
             
         }
         @istest
         public static void anotherLead () {
             project__c p = createProject();
             Lead leadObj1 =new Lead();
             leadObj1.LastName='Test Lead';
             leadObj1.MobilePhone='9860708728';
             leadObj1.Email ='test@test2.stetig';
             leadObj1.RDS_Project__c =p.Id;
             leadObj1.Budget_In_lacs__c=100; 
             
               leadObj1.Possession_Requirement__c = 'test';
             insert leadObj1;
             
             pageReference pageRef444 = page.VisitFormEditPage2;
                 Test.setCurrentPage(pageRef444);
                 
                  ApexPages.currentPage().getParameters().put('Leadid',LeadObj1.Id); 
                  ApexPages.currentPage().getParameters().put('projectId',p.Id);                 
                  NewSiteVisitController walkInForm444 = new NewSiteVisitController();
                  walkInForm444.sv.Customer_Name1__c='Mr. Aditya Marne';
                  walkInForm444.sv.Mobile_No2__c = '1234567890';
                  walkInForm444.sv.Email2__c = 'test@testing.in';
                  walkInForm444.sv.Source1__c = 'Others';
                  walkInForm444.sv.City__c = 'Pune';
                  walkInForm444.sv.Occupation__c='CA';
                  walkInForm444.sv.Sub_Source2__c ='Exhibition';
                  walkInForm444.save();
         }
             
         
         private static Project__c createProject() {
                Project__c objProject = new Project__c();
                objProject.name = 'test 1';
                objProject.Project_Code__c='test';
                insert objProject ;
            return objProject;
         } 
          private static Project__c createProject1() {
                Project__c objProject = new Project__c();
                objProject.name = 'test';
                objProject.Project_Code__c='test';
                insert objProject ;
            return objProject;
         } 
         private static Lead createleadTemplate1 () {
                Project__c p = createProject();                
                Lead objLead = new Lead();
                objLead.LastName = 'test';
                objLead.Status = 'Not Sure';
                objLead.Email = 'test@gmail.com';
                objLead.Rating = 'Hot';
                objLead.MobilePhone= '1212121212';
                objLead.LeadSource = 'Digital';
                objLead.Lead_Sub_Source__c= 'Facebook';
                objLead.LeadSource= 'Digital';
                objLead.Lead_Sub_Source__c= 'Facebook';
                objLead.RDS_Project__c = p.id; 
                objLead.RDS_Country__c= 'India';
                objLead.Budget_In_lacs__c= 100;
                insert objLead;
             return objLead;
         }
         private static Account createPAAccount () {
                List<RecordType> personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
                Account objAcc = new Account(lastName='portal account', personEmail = 'standarduser@testorg.com', personMobilePhone= '1212121212', 
                                    RecordType = personAccountRecordType[0],Mobile_No__c = '1212121212',
                                    Occupation__c = 'test',Ethnicity__c = 'test',billingstreet='Test Street',billingcity='Test City',billingstate='Test State',
                                    billingcountry='Test Country',billingpostalcode='411007');
                insert objAcc;
             return objAcc;
         }
         private static Opportunity createOpp (Id accId, Id projId) {
                
                Opportunity objOpp = new Opportunity();
                objopp.Name = 'TestOpp';
                objopp.Accountid = accId;
                objopp.CloseDate = System.today().addDays(30);
                objopp.StageName = 'Qualification';//'Unit Booked';
                objopp.Project__c = projId;
                objopp.S_Budget_In_lacs__c= 100;
                objopp.Walk_in_Source__c= 'Digital';
                objopp.Walk_in_Sub_Source__c= 'Facebook';
                insert objOpp;
                Opportunity objOppToreturn = [Select id,Project__c,AccountId ,StageName 
                                                      from Opportunity where id =:objOpp.id];
             return objOppToreturn ;
         }
         
          private static Opportunity createOpp1 (Id accId, Id projId) {
             //Account a = createPAAccount();
             //project__c p = createProject();
             
                Opportunity objOpp = new Opportunity();
                objopp.Name = 'TestOpp';
                objopp.Accountid = accId;
                objopp.CloseDate = System.today().addDays(30);
                objopp.StageName = 'Qualification';//'Unit Booked';
                objopp.Project__c = projId;
                objopp.S_Budget_In_lacs__c= 100;
                objopp.Walk_in_Source__c= 'Digital';
                objopp.Walk_in_Sub_Source__c= 'Facebook';
                insert objOpp;
                Opportunity objOppToreturn = [Select id,Project__c,AccountId ,StageName 
                                                      from Opportunity where id =:objOpp.id];
             return objOppToreturn ;
         }
         
     @isTest
         private static void WalkInSearchPageTest2() { 
             project__c p = createProject();
             Account a = createPAAccount();
          
          test.startTest();
                 pageReference pageRef = page.Site_Visit_Search_Page;
                 Test.setCurrentPage(pageRef);
                 SVsearch walkInSearch = new SVsearch ();
                 walkInSearch.strProjectId = p.Id;
                 walkInSearch.NewLead.MobilePhone= '';
                 walkInSearch.NewLead.lastName = 'testlead';
                 walkInSearch.NewLead.Email = 'testlead@test.in';
                 walkInSearch.saveMethod();
                 walkInSearch.searchAllLead();
                 
                 SVsearch walkInSearch1 = new SVsearch ();
                 
                 walkInSearch1.strProjectId = p.Id; 
                 walkInSearch1.NewLead.MobilePhone= '1212121212';
                 walkInSearch1.saveMethod();
                 walkInSearch1.searchAllLead();
               
                 SVsearch walkInSearch11= new SVsearch ();
                 Lead leadObj=new Lead();
             leadObj.LastName='Test Lead';
             leadObj.MobilePhone='9860708780';
             leadObj.RDS_Project__c =p.Id;
             insert leadObj;
             
                 walkInSearch11.strProjectId = p.Id;
                 walkInSearch11.NewLead = leadObj;
                 walkInSearch11.saveMethod();
                 walkInSearch11.searchAllLead();
                 walkInSearch11.goBack();
             test.stopTest();
         } 
 }