src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_ID_1__c</fullName>
        <label>Email ID 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_ID_2__c</fullName>
        <label>Email ID 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <label>Mobile No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Office_No__c</fullName>
        <label>Office No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Pan_Card_No__c</fullName>
        <label>Pan Card No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xcelerate_ID__c</fullName>
        <label>Xcelerate ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_ID_1__c</fullName>
        <label>Primary Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_ID_2__c</fullName>
        <label>Email ID 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <label>Mobile No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Office_No__c</fullName>
        <label>Office No.</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Pan_Card_No__c</fullName>
        <label>Pan Card No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Xcelerate_ID__c</fullName>
        <label>Xcelerate ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestChannelPartnerManagementServices.cls
@isTest
private class TestChannelPartnerManagementServices{
@isTest 
static void Testchannelpartner(){

    
    
    RecordType rt = [select Id,name from RecordType where Name ='Channel Partner' and SobjectType = 'Account']; 
    
    
    Account ac = new Account(Name='Testcp1',RecordTypeId = rt.Id,Pan_Card_No__c='4569636668',Xcelerate_ID__c='abc',Email_ID_1__c='email1@test.com',
    Email_ID_2__c='email2@test.com',Phone='9541852896',Mobile_No__c='7418529636',Office_No__c='2024567890');
    insert ac;
    
    Channel_Partner__c cp = new Channel_Partner__c(Name='Testcp1',Pan_Card_No__c='4569636668',Xcelerate_ID__c='def',Email_ID_1__c='email1@test.com',
    Email_ID_2__c='email2@test.com',Phone__c='9541852896',Mobile_No__c='7418529636',Office_No__c='2024567890');
    
    
    ChannelPartnerManagementServices cpm = new ChannelPartnerManagementServices();
    
    List<Account> accList = [SELECT Name,Pan_Card_No__c,Xcelerate_ID__c,Email_ID_1__c,Email_ID_2__c,
    Phone,Mobile_No__c,Office_No__c FROM Account WHERE Id =:ac.Id];
    
    System.debug('accList 1'+accList.size());
    
    ChannelPartnerManagementServices.insertChannelPartner(accList);
    ac.Name = 'Testcp1';
    ac.Pan_Card_No__c = '4569636674';
    ac.Xcelerate_ID__c = 'def';
    ac.Email_ID_1__c = 'email1@test.com';
    ac.Email_ID_2__c = 'email2@test.com';
    ac.Phone = '9541852896';
    ac.Mobile_No__c = '7418529636';
    ac.Office_No__c = '2024567890';
    update ac;
    System.debug('accList Size'+accList.size());
    ChannelPartnerManagementServices.updateChannelPartner(accList);
    List<Channel_Partner__c> cList = [SELECT Name,Pan_Card_No__c,Xcelerate_ID__c,Email_ID_1__c,Email_ID_2__c,
    Phone__c,Mobile_No__c,Office_No__c FROM Channel_Partner__c  WHERE Id =:ac.Id];
    System.debug('cList Size'+cList.size());
    ChannelPartnerManagementServices.deleteChannelPartner(accList);
    }
}