src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SMS_Schedule_SMS_c__c.object
<CustomObject>
    <label>SMS Schedule SMS</label>
    <nameField>
        <label>SMS Schedule SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Schedule SMS</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSMSClass.cls
@isTest
private  Class TestSMSClass{
  @isTest  
    private static void CallSMS() {
        
        //create Account
        Account acc = TestDataFactory.createPATemplate('TestPA1' , 'testleada@xanadutest.com', '9876544441', false);
        //create Project 
        Project__c p = TestDataFactory.createProject('Testsms','222');
        //create Opportunity
        List<Opportunity>  oList = TestDataFactory.createOpptyForAccount(acc.Id, p.id, 1);
        SMS_Schedule_SMS_c__c ss  = TestDataFactory.createSMSRecord(oList[0].Id);
    
    }   
}