src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Legal_Entity__c.object
<CustomObject>
    <fields>
        <fullName>RDS_Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Address2__c</fullName>
        <label>Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Company_Code__c</fullName>
        <label>Company Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RDS_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>RDS_Pin_Code__c</fullName>
        <label>Pin Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDS_Service_Tax_No__c</fullName>
        <label>Service Tax No.</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount1_Effective_Till__c</fullName>
        <label>Discount1 Effective Till</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount1_Per_Sq_Ft__c</fullName>
        <label>Discount1 Per Sq.Ft</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount1_Type__c</fullName>
        <label>Discount1 Type</label>
        <picklist>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armed Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physically Challenged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loyalty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NPV__c</fullName>
        <description>NPV Discounting rate</description>
        <label>NPV %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <externalId>true</externalId>
        <label>Project Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project_Property_Type__c</fullName>
        <label>Project Property Type</label>
        <picklist>
            <picklistValues>
                <fullName>Residential</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Pre-Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sirsa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengalaruru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Company_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Code</label>
        <referenceTo>Legal_Entity__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RDS_Interest_Rate__c</fullName>
        <label>Interest Rate %</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_Applicable_From_Floor__c</fullName>
        <label>Applicable From Floor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_Floor_Rise_Rate__c</fullName>
        <description>Floor Rise [Per Sq Ft] rate applicable for the entire project</description>
        <inlineHelpText>Floor Rise [Per Sq Ft] rate applicable for the entire project</inlineHelpText>
        <label>Floor Rise Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_Ready_Reckoner_Rate__c</fullName>
        <description>Ready reckoner rates defined by the government for this particular project location</description>
        <inlineHelpText>Ready reckoner rates defined by the government for this particular project location [Per Sq.ft Rate]</inlineHelpText>
        <label>Ready Reckoner Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_View1_PLC__c</fullName>
        <description>Per sq ft PLC rate applicable for View 1</description>
        <inlineHelpText>Per sq ft PLC rate applicable for View 1</inlineHelpText>
        <label>View1 PLC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_View2_PLC__c</fullName>
        <description>Per sq ft PLC rate applicable for View 2</description>
        <inlineHelpText>Per sq ft PLC rate applicable for View 2</inlineHelpText>
        <label>View2 PLC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_View3_PLC__c</fullName>
        <description>Per sq ft PLC rate applicable for View 1</description>
        <inlineHelpText>Per sq ft PLC rate applicable for View 1</inlineHelpText>
        <label>View3 PLC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Required_On_Token_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to indicate whether the ST component of the token amount needs to be collected as part of booking process.
If this is checked unless the entire token amount and service tax is paid, we cant proceed with the booking</description>
        <inlineHelpText>Check to indicate whether the ST component of the token amount needs to be collected as part of booking process.
If this is checked unless the entire token amount and service tax is paid, we cant proceed with the booking</inlineHelpText>
        <label>Service Tax On Token Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Token_Amount__c</fullName>
        <label>Token Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Max_Discount_Allowed__c</fullName>
        <description>Max discount allowed on this project. The rate is in Per Sq.Ft</description>
        <inlineHelpText>Max discount allowed on this project. The rate is in Per Sq.Ft</inlineHelpText>
        <label>Total Max Discount Allowed (Per Sq.Ft)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Discount1_Per_Sq_Ft__c</fullName>
        <label>Discount1 Per Sq.Ft</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount1_Type__c</fullName>
        <label>Discount1 Type</label>
        <picklist>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armed Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physically Challenged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>Legal_Entity__c</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestNewSiteVisitController.cls
@isTest
private  Class TestNewSiteVisitController{
     @isTest
    private static void TestNewSitevisitController() {
    
        Legal_Entity__c objlglentity = new Legal_Entity__c();
        objlglentity.Name ='Test stetig';
        objlglentity.RDS_Company_Code__c='123';
        objlglentity.RDS_Service_Tax_No__c= '2342627892762';
        objlglentity.RDS_Company_Name__c='Stetig';
        objlglentity.RDS_Address1__c='Pune';
        objlglentity.RDS_Address2__c='ShivajiNagar';
        objlglentity.RDS_City__c='Pune Coty';
        objlglentity.RDS_Pin_Code__c='411019';
        objlglentity.RDS_Phone__c='9953528045';
        
        
        // Project Creation
        Project__c objpr = new Project__c();
        objpr.Project_Code__c = 'T35';
        objpr.Name = 'Solitair';
        objpr.Start_Date__c = System.today().addDays(-5);
        objpr.RDS_Company_Code__c = objlglentity.Id;
        objpr.RDS_Interest_Rate__c = 12;
        objpr.Project_Stage__c='Launch';
        objpr.Address__c = '1403, Fantasy Land, Utopia, Planet Mars, OUTERWORLD CODE -11011';
        objpr.Project_Property_Type__c = 'Residential';
        objpr.S_Floor_Rise_Rate__c = 150;
        objpr.S_Applicable_From_Floor__c = 5;
        objpr.S_View1_PLC__c = 10;
        objpr.S_View2_PLC__c = 20;
        objpr.S_View3_PLC__c = 30;
        objpr.NPV__c = 12;
        objpr.S_Ready_Reckoner_Rate__c = 24000;
        objpr.Token_Amount__c = 200000;
        objpr.Service_Tax_Required_On_Token_Amount__c = true;
        objpr.Total_Max_Discount_Allowed__c = 100;
        objpr.Discount1_Type__c = 'NRI Discount';
        objpr.Discount1_Effective_Till__c = system.today().addDays(100);
        objpr.Discount1_Per_Sq_Ft__c = 1000;
        objpr.Discount2_Type__c = 'Festive Discount';
        objpr.Discount2_Effective_Till__c = system.today().addDays(100);
        objpr.Discount2_Lumpsum__c = 100000;
        objpr.Days_To_Send_Demand__c = 10;
        objpr=RDSCommon.CreateProject(objpr);
        
        // Configuration type creation
        Project_Unit_Type__c objProjectUnitType = new Project_Unit_Type__c();
        objProjectUnitType.name='ONE BHK';
        objProjectUnitType.RDS_Project__c =objpr.id;
        objProjectUnitType=RDSCommon.CreateProjectUnitType(objProjectUnitType);
        
        // tower creation 
        Tower__c t = new Tower__c();
        t.Name = 'Tower X';
        t.ProjectName__c = objpr.Id;
        t = RDSCommon.CreateTower(t);
        
        // unit creation associated to project and tower
        Project_Unit__c objPU1 = new Project_Unit__c();    
        objPU1.Name = 'TestFive';      
        objPU1.Project__c = objpr.Id;
        objPU1.Project_Unit_Type__c=objProjectUnitType.id;
        objPU1.Param1__c = '5';
        objPU1.UnitNo__c ='TestFive';
        objPU1.Unit_status__c='Vacant';
        objPU1.Actual_Area_value__c = 2218;
        objPU1.TowerName__c = t.Id;
        objPU1.Legal_Entity__c = objlglentity.id;
        objPU1=RDSCommon.CreateProjectUnit(objPU1);
        
        // account creation 
        Account objac = new Account();
        objac.FirstName = 'Shock';
        objac.LastName = 'Wave';
        objac.Project__c = objpr.Id;
        objac.Correspondence_Address__c = 'Delhi';
        objac.Category__c = 'General';
        objac.Unit__c = objPU1.Id;
        objac.PersonEmail = 'shock@transformers.com';
        objac.PersonMobilePhone = '90909090';
        objac.BillingStreet = 'ABC street';
        objac.BillingCity = 'Mumbai';
        objac.BillingState = 'Maharashtra';
        objac.BillingPostalCode = '909999';
        objac.BillingCountry = 'India';
        objac=RDSCommon.CreateAccount(objac);
        
        Opportunity objOp1 = new Opportunity();
        objOp1.Name = 'Test';
        objOp1.CloseDate = System.today();
        objOp1.AccountId = objac.Id; 
        objOp1.Status__c = 'Active'; 
        objOp1.StageName = 'Opportunity Identified'; 
        objOp1.Project__c = objpr.Id; 
        objOp1=RDSCommon.CreateOpportunity(objOp1);
        
        Opportunity objOp2 = new Opportunity();
        objOp2.Name = 'Test02';
        objOp2.CloseDate = System.today();
        objOp2.AccountId = objac.Id; 
        objOp2.Status__c = 'Active'; 
        objOp2.StageName = 'Opportunity Identified'; 
        objOp2.Project__c = objpr.Id; 
        objOp2=RDSCommon.CreateOpportunity(objOp2);
        
        Test.startTest();
              
        PageReference pRef = Page.VisitFormEditPage3;
        Test.setCurrentPage(pRef);
        Apexpages.currentPage().getParameters().put('opid', objOp1.id);
        NewSitevisitController2 sv1 = new NewSitevisitController2();        
        sv1.sv.Date_Of_Birth__c = Date.newInstance(1980,09,04);
        sv1.Assign();
        sv1.Save();
        
        /*PageReference pRef2 = Page.CustomSiteVisitFormPage;
        Test.setCurrentPage(pRef2);
        Apexpages.currentPage().getParameters().put('opid', objOp2.id);
        NewSitevisitController sv2 = new NewSitevisitController();        
        sv2.sv.Date_Of_Birth__c = Date.newInstance(1980,04,09);
        sv2.Save();*/
        
        Test.stopTest();
    }                  

}