src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank_Loan_Self_Funded__c</fullName>
        <label>Bank Loan/Self Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Project field is blank or Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Prashant Kalal </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vishal Bafna </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atul Chordia </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkin Shah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kunal T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Namonarayan Sirothiya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gaurav B.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaibhav Andhare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vishal Mantri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ravi Sharma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niket Dave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indrajit Drurwe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pratima Soni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mayank Yadav</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pooja Jadhav</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaseem Patel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nitin Deshpande</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vivek Gupta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sarfraz Syed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gaurav Herwade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yash Kothari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanmay Gore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jagrat Ranka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Namita Hiremath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunny Faldu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anurag Rangankar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Loan_Self_Funded__c</fullName>
        <label>Bank Loan/Self Funded</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Vention__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sub Vention</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TowerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TowerName</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quotation__c.object
<CustomObject>
    <description>Storing the cost sheets generated against opportunities. one of this will be used as the final cost sheet for booking as well.</description>
    <fields>
        <fullName>Finished_Unfinished__c</fullName>
        <label>Finished/Unfinished</label>
        <picklist>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unfinished</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>notEqual</operation>
                <value>Token Amount Received - BIP, Booking confirmed, Closed Lost</value>
            </filterItems>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Project__c</valueField>
            </filterItems>
            <infoMessage>Quotations can be created only on opportunities which belong to the same project as selected unit</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Subvention Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Subvention Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subvention_Charge__c</fullName>
        <label>Subvention Charge</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Tower__c.object
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuotationStartController.cls
public with sharing class QuotationStartController
{
     public string unitId{get;set;}
     public string oppId{get;set;}
     public Project_Unit__c u{get;set;}
     public Project__c proj{get;set;}
     public opportunity opp{get;set;}
     public Quotation__c qObj{get;set;}
     public List<Payment_Plan__c> payPlanList {get;set;}
     public list<SelectOption> getPlans{get;set;}
     public string selectedPlanId{get;set;}
 
     public QuotationStartController(){
            u = new Project_Unit__c ();
            proj = new Project__c();
            opp = new Opportunity();
            qObj = new Quotation__c();
            
            if(ApexPages.currentPage().getParameters().containsKey('id'))       
                unitId = (Id)ApexPages.currentPage().getParameters().get('id');    
            if(ApexPages.currentPage().getParameters().containsKey('oppId') && string.isNotBlank(ApexPages.currentPage().getParameters().get('oppId')))  
                oppId = (Id)ApexPages.currentPage().getParameters().get('oppId'); 
            
            if( string.isNotBlank(unitId)) {
                u = InventoryCostServices.getUnitDetails(unitId);
                //system.debug('u is:: '+u);
                if(u != null){
                    qObj.Project_Unit__c = u.id;
                }
                proj = InventoryCostServices.getProjectDetails(unitId);
                if(proj != null){
                    qObj.Project__c = proj.id;
                    //system.debug('proj is:: '+proj);
                }
            }
            if(string.isNotBlank(oppId)) {
                opp = [Select Id, Name, Account.Name, StageName, Sales_Manager__c from Opportunity where Id = :oppId];
                qObj.Opportunity__c = opp.Id;
            }    
       
     }   
     
     Public void populatePaymentPlan(){
     system.debug('inside plan method');
             getPlans = new list<SelectOption>();
             getPlans.add(new SelectOption('', 'Select a Payment Plan'));
             payPlanList = getPlanList(u.Project__r.Id, u.TowerName__r.Id);
             system.debug('payPlanList:: '+payPlanList);
             if(!payPlanList.isEmpty()){
                 
                  for(Payment_Plan__c pl : payPlanList){
                      getPlans.add(new SelectOption(pl.Id, pl.name));
                  }
             }
     }
     
     public pageReference startQuote(){
         boolean isError = false;
         if(qObj.Opportunity__c == null){
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select Opportunity.'));
              isError = true;
         }
         if(qObj.Project__c == null){
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select Project.'));
         }
         if(qObj.Project_Unit__c == null){
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select Project Unit.'));
              isError = true;
         }
         if(string.isBlank(qObj.Plan_Type__c)){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select Plan Type.'));
             isError = true;
         }
         if(string.isNotBlank(qObj.Plan_Type__c) && qObj.Plan_Type__c.equals('Subvention Plan') && string.isBlank(selectedPlanId)){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select Payment plan.'));
             isError = true;
         }
         
         if(!isError){
             if(string.isNotBlank(selectedPlanId)){
                 PageReference pageRef = new PageReference('/apex/Quotation2');
                 pageRef.getParameters().put('id',qObj.Project_Unit__c);
                 pageRef.getParameters().put('oppId',qObj.Opportunity__c);
                 pageRef.getParameters().put('subPlanId',selectedPlanId); 
                 pageRef.getParameters().put('Finished',qObj.Finished_Unfinished__c);
                 pageRef.getParameters().put('SubCharge',qObj.Subvention_Charge__c);
                 return pageRef;
             }
             else{
                 PageReference pageRef = new PageReference('/apex/Quotation2');
                 pageRef.getParameters().put('id',qObj.Project_Unit__c);
                 pageRef.getParameters().put('oppId',qObj.Opportunity__c);
                 pageRef.getParameters().put('Finished',qObj.Finished_Unfinished__c);
                 pageRef.getParameters().put('SubCharge',qObj.Subvention_Charge__c);
                 return pageRef;
             }
            /* if(qObj.Plan_Type__c.equals('Non Subvention Plan')){
                 PageReference pageRef = new PageReference('/apex/quotation2');
                 pageRef.getParameters().put('id',qObj.Project_Unit__c);
                 pageRef.getParameters().put('oppId',qObj.Opportunity__c);
                 //pageRef.getParameters().put('planType','Non Subvention Plan');
                 return pageRef;
             }
             if(qObj.Plan_Type__c.equals('Subvention Plan')){
                 PageReference pageRef = new PageReference('/apex/QuoteSubvention2');
                 pageRef.getParameters().put('id',qObj.Project_Unit__c);
                 pageRef.getParameters().put('oppId',qObj.Opportunity__c);
                 pageRef.getParameters().put('subPlanId',selectedPlanId); 
                 return pageRef;
             }*/
         }    
     
         return null;
         
     }
     
     public PageReference cancel() {
        pageReference pRef = ApexPages.currentPage();
        pRef.setRedirect(true);
        return pRef;
    }
    
    public static List<Payment_Plan__c> getPlanList(Id projId, Id tId) {
       // System.debug('PID:' + projId + 'Tower Id:' + tID);
        List<Payment_Plan__c> planListNew = [Select Id, Name, Bank_Loan_Self_Funded__c, Plan_Code__c,Sub_Vention__c from Payment_Plan__c where project__r.Id = : projId and tower__r.Id = :tId and Sub_Vention__c = true];
        return planListNew;
    }
    
}