src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dispatch_Mode__c</fullName>
        <label>Dispatch Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Soft Copy via Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft copy via email and hardcopy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Demand_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Return_Date__c</fullName>
        <label>Delivery/ Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_status__c</fullName>
        <label>Delivery status</label>
        <picklist>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Demand_Number__c</fullName>
        <formula>(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Customer__r.Project_Unit__r.TowerName__r.Name ,2) &amp; &apos;-&apos; &amp; Customer__r.Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT( Invoice_Date__c ) &amp; &apos;/&apos; &amp; Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Demand Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_date__c</fullName>
        <label>Dispatch date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Printed__c</fullName>
        <formula>!(ISBLANK(PO_no__c))  &amp;&amp;  !(ISBLANK(Dispatch_date__c))</formula>
        <label>Is Printed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PO_no__c</fullName>
        <label>PO no</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Invoice__c</fullName>
        <formula>HYPERLINK(&quot;/apex/DemandLetterTemplate?DemandInvId=&quot;+Id,&quot;Click Here&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Print Invoice</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_failure__c</fullName>
        <label>Reason for failure</label>
        <picklist>
            <controllingField>Delivery_status__c</controllingField>
            <picklistValues>
                <fullName>Wrong Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-existing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the payment mile stone record</description>
        <label>Standard Customer Pay Plan Detail</label>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_delivered__c</fullName>
        <formula>!(ISBLANK( Dispatch_date__c ))  &amp;&amp;  ISPICKVAL( Delivery_status__c , &quot;Delivered&quot;) &amp;&amp; 
!(ISBLANK(PO_no__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is delivered</label>
        <type>Checkbox</type>
    </fields>
    <label>Demand Invoice</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dispatch_Mode__c</fullName>
        <label>Dispatch Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Soft Copy via Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft copy via email and hardcopy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Applicants_Name__c</fullName>
        <label>Other Applicants Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Name__c</fullName>
        <label>Primary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Project field is blank or Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>Date on which the demand should be raised for this milestone. Automatically managed by the system based on the  Construction Stages</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/demandInvoicesRecon.cls
Public Class demandInvoicesRecon {
    
public List <Demand_Invoice__c> demandsInvoiceAll {get;set;}
public List <Demand_Invoice__c> demandsInv {get;set;}
public List <Demand_Invoice__c> demandsInvToUpdate {get; set;}


    public demandInvoicesRecon() 
    {
        demandsInv = new List <Demand_Invoice__c>();
        demandsInvoiceAll = [select id, name, Demand_Number__c, Customer__r.project__c, Customer__r.Primary_Name__c, Customer__r.Other_Applicants_Name__c, Customer__r.Project_Unit__c, Owner.name , PO_no__c, Dispatch_date__c, Delivery_status__c, Reason_for_failure__c, Delivery_Return_Date__c, Print_Invoice__c, Is_Printed__c, is_delivered__c, To_Update__c
                      From Demand_Invoice__c 
                      Where is_delivered__c = FALSE and Standard_Customer_Pay_Plan_Detail__r.Customer_Pay_Plan_Header__r.Booking__r.Dispatch_Mode__c = 'Soft copy via email and hardcopy' 
                      Order By Due_Date__c DESC limit 50 ];
                      
        for (demand_Invoice__c d : demandsInvoiceAll) {
            d.To_update__c = FALSE;
            demandsInv.add(d);
         }               
       
      }                

    
    public pageReference Save() 
    {
    
    demandsInvToUpdate = new List <Demand_Invoice__c>();
            
    For (Demand_Invoice__c d: demandsInv)    {
            If(d.To_update__c)    {
                demandsInvToUpdate.add(d);         
             }
         }
    
    update demandsInvToUpdate;   
    
    return null;
    
    
   }
    
    
}