src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receipts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receipt</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Receipt__c.Project_Unit__c</field>
                <operation>equals</operation>
                <valueField>$Source.Unit_No__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Receipt__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_TDS_Amount_Paid_In_Rs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total TDS Amount Paid (In Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsTDS_And_NoDemandRaised__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsTDS And NoDemandRaised</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD/Pay Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TDS_Amount_In_Rs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TDS Amount (In Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <formula>Project_Unit__r.UnitNo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit No</label>
        <type>Text</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateTotalTDSAmountOnBooking.cls
Public class UpdateTotalTDSAmountOnBooking{

public Static void calculateTDSAmount(List<receipt__c> rList){
         set<id> bookIdSet = new set<id>();
         map<id,Booking__c> bookingMap = new map<id,Booking__c>();
         decimal Amount;
         map<id,Decimal> amountMap = new map<id,Decimal>();
         list<Booking__c> bListForUpdate = new list<Booking__c>();
         
         
         
         if(rList.size() > 0){
            for(receipt__c r : rList){
                bookIdSet.add(r.Booking__c);
            }
         }
         list<Booking__c> bList = new list<Booking__c>();
         
         blist = [select id,name,Customer__c,Unit_No__c,Receipts__c,Total_TDS_Amount_Paid_In_Rs__c from booking__c where id IN : bookIdSet];   
         if(bList.size() > 0){
              for(Booking__c b : blist){
                  bookingMap.put(b.id,b);
              
              }
         }
           if(bookingMap.size() > 0){ 
               for(id key : bookingMap.keySet()){
                   Amount = 0;
                   if(rList.size() > 0){  
                     for(receipt__c r : rList){
                            if(key == r.Booking__c && r.mode__c == 'TDS' && r.IsTDS_And_NoDemandRaised__c == true && r.TDS_Amount_In_Rs__c != null){
                               Amount += r.TDS_Amount_In_Rs__c;    
                         }
                     }
                     
                 }    
                   amountMap.put(key,Amount);
               }
           }     
            if(amountMap.size() > 0){  
              for(Booking__c bObj : blist){
                    if(amountMap.containsKey(bObj.id)){
                       if(bObj.Total_TDS_Amount_Paid_In_Rs__c == null){
                          bObj.Total_TDS_Amount_Paid_In_Rs__c = 0;
                       }   
                          bObj.Total_TDS_Amount_Paid_In_Rs__c += amountMap.get(bObj.id);
                          bListForUpdate.add(bObj);
                       
                    }
              }
            }  
            if(bListForUpdate.size() > 0){
               update bListForUpdate;
            }
                   
   }
}