src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Call_Back_Date__c</fullName>
        <label>Call Back Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Call_Centre_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Centre Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BookingRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Disposition__c</fullName>
        <label>Call Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome call accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Welcome call rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong number/No Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ringing/Switched Off/Not reachable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call back request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Call_Date__c</fullName>
        <label>Last Call Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>notEqual</operation>
                <value>Booking confirmed, Closed Lost</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking (Opportunity)</relationshipLabel>
        <relationshipName>Booking1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Verification_status__c</fullName>
        <label>Document Verification Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>View_Rejected_Documents__c</fullName>
        <formula>IF(ISPICKVAL(Verification_status__c,&quot;Rejected&quot;), HYPERLINK(&quot;/apex/RejectedDocumentsPage?DocumentHeaderId=&quot;+ Document_Checklist_Header__r.Id ,&quot;Click Here&quot; ), &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View Rejected Documents</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Call_Done_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Welcome Call Done By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Booking5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physical_document_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physical Document Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Status__c</fullName>
        <label>Unit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Returned To Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Welcome Call Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - RM Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refuge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possession Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/S_ProcessDocumentVerification.cls
public class S_ProcessDocumentVerification {
    public list < booking__c > lstBooking {
        get;
        set;
    }
    public string ProcessRowNo {
        get;
        set;
    }
    public string ReleaseRowNo {
        get;
        set;
    }
    public string AssignRowNo {
        get;
        set;
    }
    public string ProfileName {
        get;
        set;
    }
    public string UserName {
        get;
        set;
    }

    public S_ProcessDocumentVerification() {
        Id profileId = userinfo.getProfileId();
        ProfileName = [Select Id, Name from Profile where Id = : profileId].Name;
        UserName = userinfo.getname();
        GetListOfBooking();
    }

    public Pagereference Process() {
        return (new PageReference('/apex/NewDocumentChecklistPage?Id=' + lstBooking[integer.valueof(ProcessRowNo)].id));
    }

    public Pagereference Release() {

        Booking__c objBooking = New Booking__c();
        objBooking.id = lstBooking[integer.valueof(ReleaseRowNo)].id;
        objBooking.Call_Centre_Rep__c = null;
        update objBooking;

        GetListOfBooking();
        return null;
    }

    public Pagereference Assign() {

        Opportunity objOpp = new Opportunity();
        objOpp.id = lstBooking[integer.valueof(AssignRowNo)].Opportunity__c;
        objOpp.Physical_document_received__c = true;
        update objOpp;

        GetListOfBooking();
        return null;
    }

    public void GetListOfBooking() {
        lstBooking = New list < booking__c > ([select id, Owner.Name, Verification_status__c, View_Rejected_Documents__c, Opportunity__c, Opportunity__r.Physical_document_received__c, Name, Last_Call_Date__c, Welcome_Call_Done_By__c, Call_Disposition__c, Call_Back_Date__c, Call_Centre_Rep__c, Customer__c, Unit_No__c, Project__r.name, Unit_No__r.Unit_Status__c, Booking_Date__c from booking__c
            where(Unit_No__r.Unit_Status__c = 'BIP - RM Verification'
                OR Unit_No__r.Unit_Status__c = 'BIP - Sales') and Opportunity__c != null ORDER BY Booking_Date__c limit 999
        ]);
    }
}