src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>notEqual</operation>
                <value>Booking confirmed, Closed Lost</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking (Opportunity)</relationshipLabel>
        <relationshipName>Booking1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Name__c</fullName>
        <label>Primary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserComponentController1.cls
public with sharing class UserComponentController1
{
    public String strBookingId {get; set;} 
    public List<Booking__c> BookingList {get;set;}
    
    
    public UserComponentController1()
    {
        
    }
    
    public void getUserDetails()
    {
        system.debug('inside Costructor');
        if(strBookingId != null)
        {
            system.debug('inside If Condition');
            BookingList = [SELECT Id,Unit_No__r.Name,Opportunity__c,Opportunity__r.Primary_Name__c,Opportunity__r.Name,Customer__c,Customer__r.Name,Customer__r.Primary_Name__c,Owner.Email,Owner.Name,Owner.Phone,Opportunity__r.Account.Salutation,Opportunity__r.Account.Name
            
            FROM Booking__c WHERE Id =:strBookingId ];
            system.debug('BookingList : ' + BookingList);
            
        }
       
    }
    
}