src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MG_Effect_Date__c</fullName>
        <label>MG Effect Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Construction_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Construction_Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Construction Stages</label>
        <referenceTo>Project_Construction_Stages__c</referenceTo>
        <relationshipLabel>Construction Stage</relationshipLabel>
        <relationshipName>Construction_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower_Name__c</fullName>
        <label>Tower Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Construction Stage</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Construction Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Stage</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Construction_Stages__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Construction_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Construction Schedule</label>
    <nameField>
        <label>Project Construction Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Construction Stages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Param2__c</fullName>
        <label>Param2</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>Date on which the demand should be raised for this milestone. Automatically managed by the system based on the  Construction Stages</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_to_be_Paid__c</fullName>
        <label>Is to be Paid</label>
        <picklist>
            <picklistValues>
                <fullName>Construction Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>From Dt. of Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>From Dt. of Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Construction_Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Construction Stages</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Construction_Stages__c.Tower__c</field>
                <operation>equals</operation>
                <valueField>$Source.Tower__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Construction_Stages__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateStandardPayPlanDueDate.cls
public class UpdateStandardPayPlanDueDate 
{
  public static void UpdateDueDate(string BookingId)
  {
   system.debug('inside update method xxxx ');
    if (BookingId != null && BookingId != '')
    {
      list<Booking__c> lstBooking = [select id, Unit_No__r.param2__c, Project__c, Customer__c, Unit_No__c, MG_Effect_Date__c
                      from Booking__c
                      where Id =: BookingId
                      and Unit_No__r.param2__c != null];
      system.debug('lstBooking vvvv '+lstBooking.size());
      if (lstBooking != null && lstBooking.size() > 0)
      {
        Booking__c ObjBooking = lstBooking[0];

        list<Construction_Stage__c> lstConsStage = [select id, Due_Date__c, Project_Construction_Stages__c
                                                            from Construction_Stage__c
                                                            where Project_Construction_Stages__r.Project__c =: ObjBooking.Project__c
                              and Tower_Name__c =: ObjBooking.Unit_No__r.param2__c
                              and Due_Date__c <=: ObjBooking.MG_Effect_Date__c];
        system.debug('lstConsStage vvvv '+lstConsStage.size());
        if (lstConsStage != null && lstConsStage.size() > 0)
        {
          Set<id> setConstStageId = new Set<id>();
          for (Construction_Stage__c objConsStage : lstConsStage)
            setConstStageId.add(objConsStage.Project_Construction_Stages__c);

          List<Standard_Customer_Pay_Plan_Detail__c> lstSCPPD = [select id, Due_Date__c
                                      from Standard_Customer_Pay_Plan_Detail__c
                                      where Is_to_be_Paid__c = 'Construction Stage'
                                      and Customer_Pay_Plan_Header__r.Project__c  =: ObjBooking.Project__c
                                      and Customer_Pay_Plan_Header__r.Customer__c =: ObjBooking.Customer__c
                                      and Customer_Pay_Plan_Header__r.Project_Unit__c =: ObjBooking.Unit_No__c
                                      and Project_Construction_Stages__c in : setConstStageId
                                      and Due_Date__c = null ];
          system.debug('lstSCPPD vvvv '+lstSCPPD.size());
          if (lstSCPPD != null && lstSCPPD.size() > 0)
          {
            for (Standard_Customer_Pay_Plan_Detail__c objSCPPD : lstSCPPD)
              objSCPPD.Due_Date__c = ObjBooking.MG_Effect_Date__c;

            update lstSCPPD;
          }
        }
      }
    }
  }
}