src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Of_Form_Receipt_From_Sales_Team__c</fullName>
        <label>Date Of Form Receipt From Sales Team</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Project_Unit_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duplicate Project Unit Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical_document_received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physical Document Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Project field is blank or Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reassign_Approval__c</fullName>
        <label>Reassign Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Release_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Release Unit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customers</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Status__c</fullName>
        <label>Unit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Returned To Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Welcome Call Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - RM Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refuge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possession Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Event_History__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Unit Event History</relationshipLabel>
        <relationshipName>Unit_Event_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Unit Event History</relationshipLabel>
        <relationshipName>Unit_Event_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Unit Event History</relationshipLabel>
        <relationshipName>Unit_Event_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Event History</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Unit Event History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Event History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    //====================================================================================================================
    // This function check the Project Unit status Vacant or not if not than throw error.
    //====================================================================================================================  
    public void insertBefore(List < Opportunity > lstOpp) {
        Set < Id > setIdofProjUnit = new Set < Id > ();

        if (lstOpp.size() > 0) {
            for (Opportunity eachOpp: lstOpp) {
                if (eachOpp.Project_Unit__c != null)
                    setIdofProjUnit.add(eachOpp.Project_Unit__c);
                if (eachOpp.Page_Running__c == true)
                    return;
            }
        }

        if (setIdofProjUnit.size() > 0) {
            List < Project_Unit__c > lstProjUnit = [Select Id, Customers__c, Unit_Status__c from Project_Unit__c Where Id IN: setIdofProjUnit];
            if (lstProjUnit.size() > 0) {
                for (Opportunity eachOpp: lstOpp) {
                    for (Project_Unit__c eachProjUnit: lstProjUnit) {
                        if (eachOpp.Project_Unit__c == eachProjUnit.Id && eachProjUnit.Unit_Status__c != null) {
                            if (eachOpp.Project_Unit__c == eachProjUnit.Id && eachProjUnit.Unit_Status__c != 'Vacant' && !Test.isRunningTest()) {
                                eachOpp.Project_Unit__c.addError('This Project Unit is not Vacant, please choose other one. Before Insert.');
                            }
                        }
                    }
                }
            }
        }
    }

    //====================================================================================================================
    // This function change the status of Project Unit and create new record in Unit Event History object.
    //====================================================================================================================
    public void insertAfter(List < Opportunity > lstOpp) {
        Set < Id > setIdofProjUnit = new Set < Id > ();
        Set < Id > setofOppId = new Set < Id > ();
        if (lstOpp.size() > 0) {
            for (Opportunity eachOpp: lstOpp) {
                if (eachOpp.Project_Unit__c != null) {
                    setIdofProjUnit.add(eachOpp.Project_Unit__c);
                    setofOppId.add(eachOpp.Id);
                    if (eachOpp.Page_Running__c == true)
                        return;
                }
            }
        }

        if (setofOppId.size() > 0) {
            List < Project_Unit__c > lstProjUnittoUpdate = [Select Id, Unit_Status__c, Customers__c from Project_Unit__c Where ID IN: setIdofProjUnit AND(Unit_Status__c = NULL OR Unit_Status__c = 'Vacant')];

            List < Opportunity > lstOpptoUpdate = new List < Opportunity > ();
            List < Unit_Event_History__c > lstUnitEventHistoryNew = new List < Unit_Event_History__c > ();

            if (lstOpp.size() > 0) {
                for (Opportunity eachOpp: lstOpp) {
                    if (eachOpp.Duplicate_Project_Unit_Request__c != false)
                        eachOpp.Duplicate_Project_Unit_Request__c = false;

                    if (lstProjUnittoUpdate.size() > 0) {
                        for (Project_Unit__c eachProjUnit: lstProjUnittoUpdate) {
                            if (eachOpp.Project_Unit__c == eachProjUnit.Id) {
                                eachProjUnit.Customers__c = eachOpp.Id;
                                eachProjUnit.Unit_Status__c = 'Hold';
                                if (eachProjUnit.Unit_Status__c == 'Hold') {
                                    Unit_Event_History__c objUnitEventHis = new Unit_Event_History__c();
                                    objUnitEventHis.Customer__c = eachOpp.Id;
                                    objUnitEventHis.Project_Unit__c = eachOpp.Project_Unit__c;
                                    objUnitEventHis.Event__c = eachProjUnit.Unit_Status__c;
                                    objUnitEventHis.Effective_Date__c = Date.today();
                                    objUnitEventHis.Created_Date__c = Date.today();
                                    objUnitEventHis.Remarks__c = 'Project Unit has been blocked';
                                    //objUnitEventHis.Booking__c = '';             //Not Create the value in Booking.

                                    lstUnitEventHistoryNew.add(objUnitEventHis);
                                }
                            }
                        }
                    }
                }

                if (lstProjUnittoUpdate.size() > 0) {
                    update lstProjUnittoUpdate;
                    if (lstUnitEventHistoryNew.size() > 0) {
                        insert lstUnitEventHistoryNew;
                    }
                }
            }
        }
    }

    //====================================================================================================================
    // This function check the Project Unit Status and throw error if not vacant. 
    // It create Unit Event History record.
    // It maintain the functionality of Approval as same for Old Project Unit request.
    //====================================================================================================================
    public void beforeUpdate(List < Opportunity > lstOpp, Map < Id, Opportunity > mapOldOppId) {
        Set < Id > setIdofProjUnit = new Set < Id > ();
        Set < Id > setofOppId = new Set < Id > ();
        if (lstOpp.size() > 0) {
            for (Opportunity eachOpp: lstOpp) {
                if (eachOpp.Project_Unit__c != null && eachOpp.Physical_document_received__c == true && mapOldOppId.get(eachOpp.Id).Physical_document_received__c == false) {
                    eachOpp.Date_Of_Form_Receipt_From_Sales_Team__c = system.today();
                } else {
                    setIdofProjUnit.add(eachOpp.Project_Unit__c);
                    setofOppId.add(eachOpp.Id);
                    if (eachOpp.Page_Running__c == true)
                        return;
                }
            }
        }

        if (setofOppId.size() > 0) {
            List < Project_Unit__c > lstProjUnittoUpdate = new List < Project_Unit__c > ();
            List < Project_Unit__c > lstProjUnit = [Select Id, Customers__r.Duplicate_Project_Unit_Request__c, Customers__r.Reassign_Approval__c, Unit_Status__c, Customers__c from Project_Unit__c Where Id IN: setIdofProjUnit OR Customers__c IN: setofOppId];
            List < Unit_Event_History__c > lstUnitEventHistoryNew = new List < Unit_Event_History__c > ();
            if (lstOpp.size() > 0) {
                for (Opportunity eachOpp: lstOpp) {
                    if (lstProjUnit.size() > 0) {
                        for (Project_Unit__c eachProjUnit: lstProjUnit) {
                            if (eachOpp.Project_Unit__c != mapOldOppId.get(eachOpp.Id).Project_Unit__c && eachProjUnit.Customers__c != eachOpp.Id && (eachProjUnit.Unit_Status__c == 'Hold' || eachProjUnit.Unit_Status__c == 'Booked' || eachProjUnit.Unit_Status__c == 'Cancelled' || eachProjUnit.Unit_Status__c == 'Sold') && eachOpp.Release_Unit__c != true) {
                                eachOpp.Project_Unit__c.addError('This Project Unit is not Vacant, please choose other one. Before Update.');
                            } else if (eachProjUnit.Id != mapOldOppId.get(eachOpp.Id).Project_Unit__c && eachOpp.Duplicate_Project_Unit_Request__c != true && (eachProjUnit.Unit_Status__c == null || eachProjUnit.Unit_Status__c == 'Vacant') && eachOpp.Release_Unit__c != true) {
                                eachProjUnit.Unit_Status__c = 'Hold';
                                eachProjUnit.Customers__c = eachOpp.Id;

                                //Updating the Unit Status and Customer of Project Unit and inserting the new Evnet History
                                if (eachProjUnit.Unit_Status__c == 'Hold') {
                                    Unit_Event_History__c objUnitEventHis = new Unit_Event_History__c();
                                    objUnitEventHis.Project_Unit__c = eachProjUnit.Id;
                                    objUnitEventHis.Event__c = eachProjUnit.Unit_Status__c;
                                    objUnitEventHis.Effective_Date__c = Date.today();
                                    objUnitEventHis.Customer__c = eachOpp.Id;

                                    objUnitEventHis.Created_Date__c = Date.today();
                                    objUnitEventHis.Remarks__c = 'Project Unit has been blocked';
                                    //objUnitEventHis.Booking__c = '';                // Not create the value of booking

                                    lstUnitEventHistoryNew.add(objUnitEventHis);
                                }
                            }
                        }
                    }
                }
            }
            if (lstUnitEventHistoryNew.size() > 0) {
                insert lstUnitEventHistoryNew;
            }
            if (lstProjUnit.size() > 0) {
                update lstProjUnit;
            }
        }
    }

    public void AfterUpdate(List < Opportunity > lstOpp, Map < Id, Opportunity > mapOldOppId) {
        Set < Id > setIdofProjUnit1 = new Set < Id > ();
        if (lstOpp.size() > 0) {
            for (Opportunity eachOpp: lstOpp) {
                if (eachOpp.Project_Unit__c != null && eachOpp.Physical_document_received__c == true && mapOldOppId.get(eachOpp.Id).Physical_document_received__c == false)
                    setIdofProjUnit1.add(eachOpp.Project_Unit__c);
            }

            list < Project_Unit__c > lstPU = [select id, Unit_Status__c from Project_Unit__c where id in : setIdofProjUnit1];

            if (lstPU != null && lstPU.size() > 0) {
                for (Opportunity eachOpp: lstOpp) {
                    if (lstPU[0].Unit_Status__c != 'BIP - Sales' && eachOpp.Physical_document_received__c == true && mapOldOppId.get(eachOpp.Id).Physical_document_received__c == false) {
                        eachOpp.Physical_document_received__c.addError('Project Unit status must be "BIP - Sales" to select this checkbox');
                    } else if (eachOpp.Physical_document_received__c == true && mapOldOppId.get(eachOpp.Id).Physical_document_received__c == false) {
                        lstPU[0].Unit_Status__c = 'BIP - RM Verification';
                    }

                }
                update lstPU;
            }
        }
    }
} // End of Class