src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Demand_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <description>Date on which Demand was raised</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Advanced_Demand__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Advanced Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the payment mile stone record</description>
        <label>Standard Customer Pay Plan Detail</label>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Demand Invoice</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Receipt__c.object
<CustomObject>
    <fields>
        <fullName>DraweeBank__c</fullName>
        <label>Drawee Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Abhyudaya Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad Mercantile Co-Op Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Janata Commercial Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Urban Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allahabad Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andaman and Nicobar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh Mahesh Co-Op Urban Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh State Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axis Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Baroda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bassein Catholic Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank (Mumbai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharati Sahakari Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bombay Mercantile Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canara Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catholic Syrian Bank Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh Rajya Sahakari Bank Maryadit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citizen Credit Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmos Co-operative Urban Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD/Pay Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Receipt_Date__c</fullName>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receipt_Status__c</fullName>
        <label>Receipt Status</label>
        <picklist>
            <picklistValues>
                <fullName>UnProcessed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Finance Submission Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Sent for Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishonored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Verification Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Customer Pay Plan Detail</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Standard_Customer_Pay_Plan_Detail__c.Customer_Pay_Plan_Header__r.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Adjustment_Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Token_Amount_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Token Amount Receipt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Token_Amount_ST__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Token Amount ST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Receipt_Details__c.object
<CustomObject>
    <fields>
        <fullName>Demand_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Demand Invoice</label>
        <referenceTo>Demand_Invoice__c</referenceTo>
        <relationshipLabel>Receipt Details</relationshipLabel>
        <relationshipName>Receipt_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Advanced_Demand__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Advanced Demand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Customer Pay Plan Detail</label>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Receipt Details</relationshipLabel>
        <relationshipName>Receipt_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Details</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Receipt Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Call_Comments__c</fullName>
        <label>Call Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>Date on which the demand should be raised for this milestone. Automatically managed by the system based on the  Construction Stages</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_to_be__c</fullName>
        <label>Is to be Paid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DemandsAndReceiptsClass.cls
Public Class DemandsAndReceiptsClass{
     Public id CPPHidpage {get;set;}
     public id Id{get;set;}
     public List <Demand_Invoice__c> Demand {get; set;}
     public List <Standard_Customer_Pay_Plan_Detail__c> SCPPDList {get; set;}
     public List <Receipt__c> Receipts{get; set;}
     public List <Receipt__c> Receiptslist{get; set;}
     public List <Receipt_Details__c> ReceiptsDetails{get; set;}
     public List <Task> tasklist{get; set;}  
     public Id what_id {get;set;}
     public Id who_id {get;set;}
     public Id scppd {get;set;}
     public List <Receipt__c> Receipts1{get;set;}
     List<Id> ReceiptsIds = new List<Id>();   
     public List<Case> caseList{get;set;}
    public DemandsAndReceiptsClass()
    {
     Receiptslist = new List<Receipt__c>();
      system.debug('&&&&&&&&&&&&&&&&');
        if(ApexPages.currentPage().getParameters().get('CPPHid') != null && ApexPages.currentPage().getParameters().get('CPPHid') != '')
         {   
             CPPHidpage  = ApexPages.currentPage().getParameters().get('CPPHid');
             Demand = [Select id, Invoice_Date__c,Due_Date__c, Name, Is_Advanced_Demand__c, Total_Amount__c, Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c, Customer__c, Customer__r.Name,
             Standard_Customer_Pay_Plan_Detail__r.Call_Comments__c From Demand_Invoice__c  Where Standard_Customer_Pay_Plan_Detail__c =: CPPHidpage];
             //Receipts = [Select id, Name,DraweeBank__c, Receipt_Date__c, Receipt_Status__c, Mode__c, Token_Amount_Receipt__c, Token_Amount_ST__c, Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c From Receipt__c Where Standard_Customer_Pay_Plan_Detail__c =: CPPHidpage];
             ReceiptsDetails = [Select id, Receipts__c, Receipts__r.Name, Receipts__r.DraweeBank__c, Receipts__r.Receipt_Date__c, Receipts__r.Receipt_Status__c, Receipts__r.Mode__c, Receipts__r.Token_Amount_Receipt__c, Receipts__r.Token_Amount_ST__c, Receipts__r.Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c From Receipt_Details__c Where Standard_Customer_Pay_Plan_Detail__c =: CPPHidpage];
            
            for(Receipt_Details__c rd: ReceiptsDetails){ 
                ReceiptsIds.add(rd.Receipts__c); 
             }
             System.Debug('ReceiptsIds'+ReceiptsIds);
             System.Debug('ReceiptsIds Size'+ReceiptsIds.size());
             Set<Id> mySet = new Set<Id>();
             if(ReceiptsIds.size() > 0)
             {
                 mySet.addAll(ReceiptsIds);
             }
             System.Debug('Set'+mySet);
             System.Debug('ReceiptsIds'+ReceiptsIds);
             Receipts = new List<Receipt__c>();
             if(ReceiptsIds.size() > 0)
             {
                 Receipts = [Select id, Name,DraweeBank__c, Receipt_Date__c, Receipt_Status__c, Mode__c, Token_Amount_Receipt__c, Token_Amount_ST__c,Receipt_Against__c, Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c From Receipt__c Where id in : ReceiptsIds];
             }
             if(Receipts.size() > 0)
             {
                 system.debug('Receipts1  '+Receipts);
                 system.debug('Receipts1  '+Receipts.size());
             }
             System.Debug('before task query');
             tasklist = [Select id, ActivityDate, Communication_Type__c,Reason_For_Call__c, Next_Action_Date__c,PTP_Amount__c,Payment_Instrument__c,Address__c, Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c,L2__c,L3__c From Task where Standard_Customer_Pay_Plan_Detail__c =:CPPHidpage];
             System.Debug('taskList'+tasklist);
             SCPPDList = [Select Is_to_be__c,Customer_Pay_Plan_Header__r.Customer__r.Project__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Project_Unit__r.Name, Customer_Pay_Plan_Header__r.Customer__r.Name, Customer_Pay_Plan_Header__r.Customer__c, Customer_Pay_Plan_Header__r.Customer__r.Account.Name, Customer_Pay_Plan_Header__r.Customer__r.Account.Id from Standard_Customer_Pay_Plan_Detail__c where Id =:CPPHidpage];
             System.Debug('SCPPDList'+SCPPDList);
        }
      
          
       if(ApexPages.currentPage().getParameters().get('Id') != null && ApexPages.currentPage().getParameters().get('Id') != '')
       {   
           Id= ApexPages.currentPage().getParameters().get('Id');
           system.debug('Id====='+Id);
           system.debug('Inside the method');
           Receiptslist= [Select id, Name,DraweeBank__c, Receipt_Date__c, Receipt_Status__c, Mode__c, Token_Amount_Receipt__c, Token_Amount_ST__c,Receipt_Against__c, Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c From Receipt__c Where Booking__c =:Id];
           system.debug('Receiptslist'+Receiptslist);            
       }
       //Added by shailesh to show Collection related History//
       if(SCPPDList != null)
       {
           system.debug('Id====='+Id);
           caseList = [Select Id,Origin,Mode__c,Reason,L1__c,L2__c,L3__c,L4__c,Priority,Status,Reason_Outcome__c,AccountId,ContactId,CaseNumber,CreatedDate
                              ,ClosedDate,Attempted_By__c from Case where AccountId =: SCPPDList[0].Customer_Pay_Plan_Header__r.Customer__r.AccountId and L1__c = 'Collection Related'];
           System.debug('CASE LIST::'+caseList);
       }
    
   }
    
    public PageReference redirectUser(){    
    String subject = 'Post Sales Call';
    String status = 'Completed';
    String tasktype = 'Post Sales Call';
    String retURL = '/apex/DemandsAndReceipts?CPPHid='+CPPHidpage;
    String SaveURL = retURL;
    String CancelURL= retURL;
    String OppName ='';
    if( SCPPDList.size()>0)
    {
        what_id = SCPPDList[0].Customer_Pay_Plan_Header__r.Customer__c;
        who_id = SCPPDList[0].Customer_Pay_Plan_Header__r.Customer__r.Account.Id;    
        scppd = CPPHidpage;
        OppName = SCPPDList[0].Customer_Pay_Plan_Header__r.Customer__r.Name;      
    } 
    ///////////////////////// -------------------------------- commented by vikas for new case ------------------------------------////////////////////////////
    //PageReference ref = new PageReference('/apex/CallAttemptEditPage2?subject='+subject+'&status='+status+'&tasktype='+tasktype+'&origin=Page&who_id='+who_id+'&what_id='+what_id+'&scppd='+scppd+'&retURL='+retURL+'&CancelURL='+retURL+'&SaveURL='+retURL);
    /////////////////////// ----------------------- Added by vikas for new case ----------------------------------------------////////////////////////////////
    PageReference ref = new PageReference('/500/e?CF00NR0000001pLyN='+OppName+'&def_account_id='+who_id+'&retURL='+retURL+'&CancelURL='+retURL+'&SaveURL='+retURL); //// CF00NR0000001pLyN this id of opportunity name field from case view source page 
    //ref += 'subject='+subject; 

    
    //subject=Post%20Sales%20Call&status=Completed&tasktype=Post%20Sales%20Call&origin=Page&who_id=001O000000miUf5IAE&what_id=006O0000007k74QIAQ&retURL=/006O0000007k74QIAQ&saveURL=/006O0000007k74QIAQ&cancelURL=/006O0000007k74QIAQ
    
    
    return ref;
}
}