src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>notEqual</operation>
                <value>Booking confirmed, Closed Lost</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking (Opportunity)</relationshipLabel>
        <relationshipName>Booking1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <picklist>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cheque_DD_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_DD__c</fullName>
        <label>Cheque/DD No.</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>Indian Rupee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK Pound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubai Dirham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kuwaiti Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saudi Riyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese Yen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese Yuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>European Euro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DraweeBank__c</fullName>
        <label>Drawee Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Abhyudaya Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad Mercantile Co-Op Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Janata Commercial Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Urban Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allahabad Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andaman and Nicobar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh Mahesh Co-Op Urban Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh State Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axis Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Baroda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bassein Catholic Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank (Mumbai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharati Sahakari Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bombay Mercantile Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canara Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catholic Syrian Bank Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh Rajya Sahakari Bank Maryadit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citizen Credit Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmos Co-operative Urban Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Drawn_in_favour_of__c</fullName>
        <label>Drawn in favour of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Receipt_Date__c</fullName>
        <label>Manual Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD/Pay Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Account_Money__c</fullName>
        <label>On Account Money</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Project__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Print_Receipt_On_Letterhead__c</fullName>
        <formula>HYPERLINK(&quot;/apex/S_PrintReceipt?id=&quot;+Id+&quot;&amp;letterhead=&quot;+&apos;1&apos;,&quot;Click Here&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Print Receipt On Letterhead</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_Receipt__c</fullName>
        <formula>HYPERLINK(&quot;/apex/S_PrintReceipt?id=&quot;+Id+&quot;&amp;letterhead=&quot;+&apos;0&apos;,&quot;Click Here&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Print Receipt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receipt_Date__c</fullName>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receipt_Status__c</fullName>
        <label>Receipt Status</label>
        <picklist>
            <picklistValues>
                <fullName>UnProcessed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Finance Submission Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Sent for Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishonored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Verification Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Customer Pay Plan Detail</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Standard_Customer_Pay_Plan_Detail__c.Customer_Pay_Plan_Header__r.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Adjustment_Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Token_Amount_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Token Amount Receipt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Token_Amount_ST__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Token Amount ST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Is_to_be__c</fullName>
        <label>Is to be Paid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/S_PaymentsPaidClass.cls
public class S_PaymentsPaidClass
{
    public string errorMsg {get;set;}
    public List<Receipt__c> objR {get;set;}
    public id bid {get;set;}
    public S_PaymentsPaidClass()
    {
        errorMsg = '';
        if(ApexPages.currentPage().getParameters().get('Bookingid')!='')
        bid = ApexPages.currentPage().getParameters().get('Bookingid');
        objR = new List<Receipt__c>();                   
        objR = [Select id, Name,DraweeBank__c,Booking__c, On_Account_Money__c, Currency__c, Receipt_Date__c, Receipt_Status__c, Mode__c, Token_Amount_Receipt__c, Token_Amount_ST__c, 
        Standard_Customer_Pay_Plan_Detail__r.Is_to_be__c, Total_Amount__c, Cheque_DD__c, Cheque_DD_Date__c ,Opportunity__c, Booking_Status__c, Drawn_in_favour_of__c, Print_Receipt__c, Manual_Receipt_Date__c, Print_Receipt_On_Letterhead__c
        From Receipt__c where Booking__c = : bid];
        
       
      
    }
    
   
 
   
}