src/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Future_Correspondence_Contact_Name__c</fullName>
        <label>Future Correspondence Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Correspondence_Contact_Phone__c</fullName>
        <label>Future Correspondence Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Future_Correspondence_Contact_Relation__c</fullName>
        <label>Future Correspondence Contact Relation</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quotation</label>
        <referenceTo>Quotation__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Vacant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Booking</relationshipLabel>
        <relationshipName>Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Amount__c</fullName>
        <label>Total Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Demand_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Customer_Pay_Plan_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the payment mile stone record</description>
        <label>Standard Customer Pay Plan Detail</label>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Demand Invoices</relationshipLabel>
        <relationshipName>Demand_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demand Invoice</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Future_Correspondence_Contact_Name__c</fullName>
        <label>Future_Correspondence_Contact_Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Correspondence_Contact_Phone__c</fullName>
        <label>Future_Correspondence_Contact_Phone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Waiver__c</fullName>
        <formula>Total_Interest__c -  Total_Interest_Settled__c -  Total_Waiver__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Interest Pending Waiver</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quotation__c.object
<CustomObject>
    <description>Storing the cost sheets generated against opportunities. one of this will be used as the final cost sheet for booking as well.</description>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Quotations</relationshipLabel>
        <relationshipName>Quotations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Billed amount for charge type [basic, utilities, infra, legal etc.,]</description>
        <label>Installment Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charge_Amount_Due__c</fullName>
        <formula>Charge_Amount_Billed__c -  Charge_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installment Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charge_Amount_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount received from customer against the billed amount</description>
        <label>Installment Amount (Paid)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPaymentOverdue__c</fullName>
        <formula>AND((Payment_Due_Date__c &lt;  TODAY()),OR((Charge_Amount_Due__c &gt; 0), (Service_Tax_Amount_Due__c &gt;0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This flag indicates if a payment is overdue.</inlineHelpText>
        <label>IsPaymentOverdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_to_be__c</fullName>
        <label>Is to be Paid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Call_Disposition__c</fullName>
        <label>Last Call Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Promised to pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asked to call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need to call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PTP_Amount__c</fullName>
        <label>PTP Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PTP_Date__c</fullName>
        <label>PTP Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PTP_Instrument__c</fullName>
        <label>PTP Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demand Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RTGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of service tax for which invoice has been raised</description>
        <label>Service Tax Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Due__c</fullName>
        <formula>Service_Tax_Amount_Billed__c -  Service_Tax_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Tax Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/S_CollectionsDashboardClass.cls
public with sharing class S_CollectionsDashboardClass 
{
    public string errorMsg {get;set;}
    public datetime dtSelectedDate {get;set;}
    public string selectedProjectId {get;set;}
    public string selectedDisposition {get;set;}   
    public string selectedRM {get;set;} 
    
    public string selectedConsStageId {get;set;}
    public string selectedCriteria {get;set;}
    public string selectedTowerId {get;set;}
    public Standard_Customer_Pay_Plan_Detail__c objSCPPD {get;set;}
    public List<Standard_Customer_Pay_Plan_Detail__c> objSCPPD2 {get;set;}
    public List<Standard_Customer_Pay_Plan_Detail__c> objSCPPD3 {get;set;}
    public Standard_Customer_Pay_Plan_Detail__c objSCPPD1 {get;set;}
    public list<DemandManagementServices.wrpCustomers> lstCustomers {get;set;} 
    public list<DemandManagementServices.wrpCustomers> pendingDemandsList {get;set;} 
    public Map<String, list<DemandManagementServices.wrpCustomers>> customerTowerMap  {get;set;}
    public Set<String> towerNames {get;set;}
    public list<DemandManagementServices.wrpCustomers> customerTowerList {get;set;}
    public List<Booking__c> lstBooking {get; set;}
    public String strBookingId {get; set;}
    public id selectedPlan {get; set;}
    public List <Demand_Invoice__c> Demand {get; set;}
    
    public String ChargeAmt {get; set;}
    public List <String> ListChargeAmt {get; set;}
    
    public List < wrapperclass> wrapperscppdList{get; set;}
       public class wrapperclass
    {
        public String Amount1{ get; set; }
        public String Amount2{ get; set; }
        public String Amount3{ get; set; }
        public String Amount4{ get; set; }
        public String Amount5{ get; set; }
        public String Amount6{ get; set; }
        public Standard_Customer_Pay_Plan_Detail__c stdCustomerPayPlan {get;set;}
        public wrapperclass(Standard_Customer_Pay_Plan_Detail__c s, Decimal d, Decimal d2, Decimal d3,Decimal d4,Decimal d5, Decimal d6)
        {
            stdCustomerPayPlan = s;
            if(d6!=null) d= d+d6;
            Amount1=QuotationManagementServices.INFormat(d);
            Amount2=QuotationManagementServices.INFormat(d2);
            Amount3=QuotationManagementServices.INFormat(d3);
            if(d4 != null)
            {
                Amount4=QuotationManagementServices.INFormat(d4);
            }
            if(d5 != null)
            {
                Amount5=QuotationManagementServices.INFormat(d5);
            }
        }
    } 
       
    public S_CollectionsDashboardClass()
    {
        errorMsg = '';
        objSCPPD = new Standard_Customer_Pay_Plan_Detail__c();
        objSCPPD1 = new Standard_Customer_Pay_Plan_Detail__c();
        objSCPPD2 = new List<Standard_Customer_Pay_Plan_Detail__c>();
        objSCPPD3 = new List<Standard_Customer_Pay_Plan_Detail__c>();
        lstCustomers = new list<DemandManagementServices.wrpCustomers>();
        Demand = new List<Demand_Invoice__c>();
        pendingDemandsList = null;
        towerNames = null;
     
    }
    
    public pageReference getCollectionsList()
    {
         if(selectedProjectId != null)
        {
            if(selectedDisposition != 'All' && selectedRM == 'All')
            {
                // Fetching the SCPPD records            
                objSCPPD2 = [Select PTP_Date__c,Id,Name,Customer_Pay_Plan_Header__r.Customer__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Account.Id,Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c,Total_Interest_Amount__c,
                Customer_Pay_Plan_Header__r.Customer__r.Account.PersonMobilePhone,Customer_Pay_Plan_Header__r.Booking__r.Unit_No__r.Name,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Relation__c,
                Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Name__c,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Phone__c,
                Customer_Pay_Plan_Header__r.Customer__c, Is_to_be__c, Charge_Amount_Billed__c, Charge_Amount_Due__c, Charge_Amount_Paid__c, 
                 PTP_Amount__c,PTP_Instrument__c, IsPaymentOverdue__c, Last_Call_Disposition__c,Service_Tax_Amount_Billed__c, Service_Tax_Amount_Due__c,Customer_Pay_Plan_Header__r.Quotation__r.Booking__r.Owner.Name,
                Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c,Customer_Pay_Plan_Header__r.Booking__r.Owner.Name, L2__c,L3__c 
                From Standard_Customer_Pay_Plan_Detail__c 
                //where (((Charge_Amount_Due__c >0 and PTP_Date__c = null) or (Charge_Amount_Due__c >0 and PTP_Date__c < :System.today()))
                where ((Charge_Amount_Due__c >0)
                and Project__c =: selectedProjectId and L2__c =:selectedDisposition)];
                //and Project__c =: selectedProjectId and Last_Call_Disposition__c =:selectedDisposition)];
                //System.debug('HHHHHHHHHHHHHHHHHHH' +objSCPPD2[0].Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c);
            }
            else if(selectedDisposition != 'All' && selectedRM != 'All')
            {
                objSCPPD2 = [Select PTP_Date__c,Id,Name,Customer_Pay_Plan_Header__r.Customer__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Account.Id,Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c,Total_Interest_Amount__c,
                Customer_Pay_Plan_Header__r.Customer__r.Account.PersonMobilePhone,Customer_Pay_Plan_Header__r.Booking__r.Unit_No__r.Name,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Relation__c,
                Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Name__c,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Phone__c,
                Customer_Pay_Plan_Header__r.Customer__c, Is_to_be__c, Charge_Amount_Billed__c, Charge_Amount_Due__c, Charge_Amount_Paid__c, 
                 PTP_Amount__c,PTP_Instrument__c, IsPaymentOverdue__c, Last_Call_Disposition__c,Service_Tax_Amount_Billed__c, Service_Tax_Amount_Due__c,Customer_Pay_Plan_Header__r.Quotation__r.Booking__r.Owner.Name,
                Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c,Customer_Pay_Plan_Header__r.Booking__r.Owner.Name, L2__c,L3__c 
                From Standard_Customer_Pay_Plan_Detail__c 
                where ((Charge_Amount_Due__c >0)
                //where (((Charge_Amount_Due__c >0 and PTP_Date__c = null) or (Charge_Amount_Due__c >0 and PTP_Date__c < :System.today()))
                and Project__c =: selectedProjectId and L2__c =:selectedDisposition and Customer_Pay_Plan_Header__r.Booking__r.Owner.Name =:selectedRM)];
            }
            else if(selectedDisposition == 'All' && selectedRM != 'All' )
            {
                objSCPPD2 = [Select PTP_Date__c,Id,Name,Customer_Pay_Plan_Header__r.Customer__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Account.Id,Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c,Total_Interest_Amount__c,
                Customer_Pay_Plan_Header__r.Customer__r.Account.PersonMobilePhone,Customer_Pay_Plan_Header__r.Booking__r.Unit_No__r.Name,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Relation__c,
                Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Name__c,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Phone__c,
                Customer_Pay_Plan_Header__r.Customer__c, Is_to_be__c, Charge_Amount_Billed__c, Charge_Amount_Due__c, Charge_Amount_Paid__c, 
                PTP_Amount__c,PTP_Instrument__c, IsPaymentOverdue__c, Last_Call_Disposition__c,Service_Tax_Amount_Billed__c, Service_Tax_Amount_Due__c,Customer_Pay_Plan_Header__r.Quotation__r.Booking__r.Owner.Name,
                Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c,Customer_Pay_Plan_Header__r.Booking__r.Owner.Name, L2__c,L3__c 
                From Standard_Customer_Pay_Plan_Detail__c 
                where ((Charge_Amount_Due__c >0)
                //where (((Charge_Amount_Due__c >0 and PTP_Date__c = null) or (Charge_Amount_Due__c >0 and PTP_Date__c < :System.today()))
                and Project__c =: selectedProjectId and Customer_Pay_Plan_Header__r.Booking__r.Owner.Name =:selectedRM)];
            }
            else
            {
                objSCPPD2 = [Select PTP_Date__c,Id,Name,Customer_Pay_Plan_Header__r.Customer__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Account.Id,Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c,Total_Interest_Amount__c,
                Customer_Pay_Plan_Header__r.Customer__r.Account.PersonMobilePhone,Customer_Pay_Plan_Header__r.Booking__r.Unit_No__r.Name,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Relation__c,
                Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Name__c,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Phone__c,
                Customer_Pay_Plan_Header__r.Customer__c, Is_to_be__c, Charge_Amount_Billed__c, Charge_Amount_Due__c, Charge_Amount_Paid__c, 
                PTP_Amount__c,PTP_Instrument__c, IsPaymentOverdue__c, Last_Call_Disposition__c,Service_Tax_Amount_Billed__c, Service_Tax_Amount_Due__c,Customer_Pay_Plan_Header__r.Quotation__r.Booking__r.Owner.Name,
                Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c,Customer_Pay_Plan_Header__r.Booking__r.Owner.Name, L2__c,L3__c 
                From Standard_Customer_Pay_Plan_Detail__c 
                where ((Charge_Amount_Due__c >0)
                //where (((Charge_Amount_Due__c >0 and PTP_Date__c = null) or (Charge_Amount_Due__c >0 and PTP_Date__c < :System.today()))
                and Project__c =: selectedProjectId )];
            
            }

            if(objSCPPD2.size() > 0)
            {
                for(Standard_Customer_Pay_Plan_Detail__c  ss :  objSCPPD2)
                {
                    if( ss.Total_Interest_Amount__c != null){
                        ss.Total_Interest_Amount__c = ss.Total_Interest_Amount__c.setScale(0); 
                    }
                     //ChargeAmt  = QuotationManagementServices.INFormat(ss.Charge_Amount_Billed__c);
                     //ListChargeAmt.add(ChargeAmt);
                }
            }
            
                            
         }
        // Documentcheck list page sends Booking id here.
        if(ApexPages.currentPage().getParameters().get('bookingId') != null && ApexPages.currentPage().getParameters().get('bookingId') != '')
        {
            strBookingId = ApexPages.currentPage().getParameters().get('bookingId');        
            lstBooking = [Select Id, Project__c, Project__r.Name, Customer__c from Booking__c Where Id =: strBookingId];
            //if(lstBooking != null && lstBooking.size() > 0)
              //  search();
        }
      //  getTowerNames();
      
      
            wrapperscppdList = new List<wrapperclass>();
            for (integer i = 0 ; i < objSCPPD2.size() ; i++)
            {
               wrapperscppdList.add(new wrapperclass(objSCPPD2[i], objSCPPD2[i].Charge_Amount_Billed__c, objSCPPD2[i].Charge_Amount_Due__c,objSCPPD2[i].Service_Tax_Amount_Due__c,objSCPPD2[i].PTP_Amount__c ,objSCPPD2[i].Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c, objSCPPD2[i].Service_Tax_Amount_Billed__c ));//,objSCPPD2[i].Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c
               
            } 
      
            System.debug('wrapperscppdList' +wrapperscppdList);
            
            return null;
    
    }
    
    public pageReference getDemandReciepts(){
    
    System.debug('selectedPlan  ' +selectedPlan);
    Customer_Pay_Plan_Header__c CPPH3  =  new  Customer_Pay_Plan_Header__c();
    CPPH3  = [Select id, Name,Customer__c from Customer_Pay_Plan_Header__c where id =: selectedPlan];
    Demand = [Select id, Name,Customer__c From Demand_Invoice__c  Where Customer__c =: CPPH3.Customer__c];
    return null;
    }
   
   /* public list<SelectOption> searchOptions
    {
        get
        {
          list<SelectOption> searchOptions = new list<SelectOption>();
             searchOptions.add(new SelectOption('Construction Stage', 'Construction Stage'));
             searchOptions.add(new SelectOption('Due Date', 'Due Date'));
            return searchOptions;
        }
        set;
    }*/
    
    

    public list<SelectOption> lstProjects 
    {
        get
        {
          lstProjects = null;
            list<SelectOption> lstTempProjects = new list<SelectOption>();
            lstTempProjects.add(new SelectOption('', '--Select Project--'));
            for(Project__c objProj : [select id, name from Project__c])
            {
                if(objProj.name != null)
                    lstTempProjects.add(new SelectOption(objProj.id, objProj.name));
            }
            return lstTempProjects;
        }
        set;
    }
    
   /* public list<SelectOption> lstStructionStages
    {
        get
        {
            errorMsg = '';
            list<SelectOption> lstTempStructionStages = new list<SelectOption>();
            lstTempStructionStages.add(new SelectOption('', '--None--'));
            if(selectedProjectId != null && selectedProjectId != '')
            {
                list<Project_Construction_Stages__c> lstConsStage = [select id, name, Sequence_No__c 
                                                                        from Project_Construction_Stages__c  
                                                                        where Project__c =: selectedProjectId 
                                                                        and tower__c = :selectedTowerId
                                                                        order by Sequence_No__c ];
                if(lstConsStage != null && lstConsStage.size() > 0)
                {
                    for(Project_Construction_Stages__c objPCS : lstConsStage )
                    {
                        if(objPCS.name != null)
                            lstTempStructionStages.add(new SelectOption(objPCS.id, objPCS.name));
                    }
                }
                else
                    errorMsg = 'Project Construction Stage not found.';
                
            }
            return lstTempStructionStages;
        }
        set;
    }
     */ 
    public list<SelectOption> lstTower
    {
        get
        {
            Set<String> stString = new Set<String>();
            errorMsg = '';
            list<SelectOption> lstTempTower = new list<SelectOption>();
            lstTempTower.add(new SelectOption('', '--None--'));
            if(selectedProjectId != null && selectedProjectId != '')
            {
                List<Tower__c> lstTowerName = new List<Tower__c>([Select Id, Name from  Tower__c where  ProjectName__c =:selectedProjectId order by Name]);
                if(lstTowerName != null && lstTowerName.size() > 0)
                {
                    for(Tower__c obj1 : lstTowerName ){
                       lstTempTower.add(new SelectOption(obj1.Id, obj1.Name));
                    }
                }
                else
                    errorMsg = 'Project Tower not found.';
                
            }
            return lstTempTower;
        }
        set;
    }
    
    public list<SelectOption> getRMs
    {
        get
        {
            Set<String> stRMs = new Set<String>();
            errorMsg = '';
            list<SelectOption> lstTempRM = new list<SelectOption>();
            lstTempRM.add(new SelectOption('All', 'Select a RM'));
            if(selectedProjectId != null && selectedProjectId != '')
            {
                
                objSCPPD3 = [Select PTP_Date__c,Id,Name,Customer_Pay_Plan_Header__r.Customer__r.Name,Customer_Pay_Plan_Header__r.Customer__r.Account.Id,Customer_Pay_Plan_Header__r.Customer__r.Total_Interest_Waiver__c,Total_Interest_Amount__c,
                Customer_Pay_Plan_Header__r.Customer__r.Account.PersonMobilePhone,Customer_Pay_Plan_Header__r.Booking__r.Unit_No__r.Name,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Relation__c,
                Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Name__c,Customer_Pay_Plan_Header__r.Booking__r.Future_Correspondence_Contact_Phone__c,
                Customer_Pay_Plan_Header__r.Customer__c, Is_to_be__c, Charge_Amount_Billed__c, Charge_Amount_Due__c, Charge_Amount_Paid__c, 
                 PTP_Amount__c,PTP_Instrument__c, IsPaymentOverdue__c, Last_Call_Disposition__c,Service_Tax_Amount_Billed__c, Service_Tax_Amount_Due__c,Customer_Pay_Plan_Header__r.Quotation__r.Booking__r.Owner.Name,
                Customer_Pay_Plan_Header__r.Booking__r.Funding_Status__c,Customer_Pay_Plan_Header__r.Booking__r.Owner.Name
                From Standard_Customer_Pay_Plan_Detail__c 
                where (((Charge_Amount_Due__c >0 and PTP_Date__c = null) or (Charge_Amount_Due__c >0 and PTP_Date__c < :System.today()))
                and Project__c =: selectedProjectId )];
                
              
                if(objSCPPD3 != null && objSCPPD3.size() > 0)
                {
                    for(Standard_Customer_Pay_Plan_Detail__c y : objSCPPD3)
                    {
                        if(y.Customer_Pay_Plan_Header__r.Booking__r.Owner.Name != null)
                        {
                           stRMs.add(y.Customer_Pay_Plan_Header__r.Booking__r.Owner.Name);
                        }
                    }
                    System.Debug('RM set'+stRMs);
                }
                else
                    errorMsg = 'No RMs found.';
               
               for (String r : stRMs) 
               {
                    lstTempRM.add(new SelectOption(r, r));
               }
                    
                    
                
            }
            return lstTempRM;
        }
        set;
    }
    
    
    public void dummy(){
      
    }
    
    // retrieves the row wrapper containing the wrapped tower name headings
   /** public Set<String> getTowerNames()
    {
      
        if(pendingDemandsList == null)  {
          towerNames = new Set<String>();
          customerTowerMap = new Map<String, list<DemandManagementServices.wrpCustomers>>();
          pendingDemandsList = new list<DemandManagementServices.wrpCustomers>(); 
          pendingDemandsList = DemandManagementServices.searchAllPendingDemands();
          for(DemandManagementServices.wrpCustomers pdc : pendingDemandsList) {
            System.debug('Customer details:' + pdc);
            if(customerTowerMap.containsKey(pdc.projectName + '-' +pdc.towerName))
              customerTowerMap.get(pdc.projectName + '-' +pdc.towerName).add(pdc);
            else {
              list<DemandManagementServices.wrpCustomers> customerTowerWise = new list<DemandManagementServices.wrpCustomers>();
              customerTowerWise.add(pdc);
              customerTowerMap.put(pdc.projectName + '-' +pdc.towerName, customerTowerWise);
            }
            towerNames.add(pdc.projectName + '-' +pdc.towerName);
          }
        }
        System.debug('Tower Names:' + towernames);
        System.debug('customerTowerMap:' + customerTowerMap);
        if(pendingDemandsList.size()  >0){
          return towerNames;
        }

        return null;
    }
    
    public void getCustomersTowerWise() {
      customerTowerList = new list<DemandManagementServices.wrpCustomers>();
      String towerName = Apexpages.currentPage().getParameters().get('towerName');
      System.debug('Tower Name in get customers : customerTowerMap' + towerName + customerTowerMap);
      if(pendingDemandsList == null)  {
      getTowerNames();
      } 
      if(customerTowerMap.containsKey(towerName))
        customerTowerList = customerTowerMap.get(towerName);
      System.debug('Customer Tower List:' + customerTowerList);
    } **/
 
   
}