src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Amount__c</fullName>
        <label>Total Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>RDS_Interest_Rate__c</fullName>
        <label>Interest Rate %</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Billed amount for charge type [basic, utilities, infra, legal etc.,]</description>
        <label>Installment Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charge_Amount_Due__c</fullName>
        <formula>Charge_Amount_Billed__c -  Charge_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installment Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPaymentOverdue__c</fullName>
        <formula>AND((Payment_Due_Date__c &lt;  TODAY()),OR((Charge_Amount_Due__c &gt; 0), (Service_Tax_Amount_Due__c &gt;0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This flag indicates if a payment is overdue.</inlineHelpText>
        <label>IsPaymentOverdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of service tax for which invoice has been raised</description>
        <label>Service Tax Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Due__c</fullName>
        <formula>Service_Tax_Amount_Billed__c -  Service_Tax_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Tax Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Interest Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CalculateInterestSchedular.cls
global class CalculateInterestSchedular implements Schedulable{ 
  global void execute(SchedulableContext sc)
  {
        system.debug('Here in Schedular class');
        List <Standard_Customer_Pay_Plan_Detail__c> ListSCPPDobj = new List<Standard_Customer_Pay_Plan_Detail__c>();
        ListSCPPDobj = [Select Id,Name,IsPaymentOverdue__c,Total_Interest_Amount__c,Customer_Pay_Plan_Header__c,Customer_Pay_Plan_Header__r.Customer__c,
        Customer_Pay_Plan_Header__r.Project__r.RDS_Interest_Rate__c,Charge_Amount_Due__c,Service_Tax_Amount_Due__c,Charge_Amount_Billed__c,Service_Tax_Amount_Billed__c from Standard_Customer_Pay_Plan_Detail__c  Where IsPaymentOverdue__c =: True And Customer_Pay_Plan_Header__c != null];
        System.debug('List Of SCPPD:' +ListSCPPDobj);
        if(ListSCPPDobj.size()>0)
        {
            System.Debug('Call the CalculateInterest Class');
            CalculateInterestClass.CalculateInterest(ListSCPPDobj);
        }
        else
        {
            System.Debug('Do Nothing.');
        }
    }
}