src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Billed amount for charge type [basic, utilities, infra, legal etc.,]</description>
        <label>Installment Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charge_Amount_Due__c</fullName>
        <formula>Charge_Amount_Billed__c -  Charge_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installment Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsPaymentOverdue__c</fullName>
        <formula>AND((Payment_Due_Date__c &lt;  TODAY()),OR((Charge_Amount_Due__c &gt; 0), (Service_Tax_Amount_Due__c &gt;0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This flag indicates if a payment is overdue.</inlineHelpText>
        <label>IsPaymentOverdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marked_for_Interest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marked for Interest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Date__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of service tax for which invoice has been raised</description>
        <label>Service Tax Amount (Demanded)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount_Due__c</fullName>
        <formula>Service_Tax_Amount_Billed__c -  Service_Tax_Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Tax Amount (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MarkForInterestBatch.cls
global class MarkForInterestBatch implements Database.Batchable <sObject>, Schedulable 
{
     Public String Query;
    
    public MarkForInterestBatch() 
    {
     Query = 'Select Id,Charge_Amount_Billed__c,Charge_Amount_Due__c,Service_Tax_Amount_Due__c,Service_Tax_Amount_Billed__c,Customer_Pay_Plan_Header__r.Customer__c,Payment_Due_Date__c,Project__c FROM Standard_Customer_Pay_Plan_Detail__c WHERE IsPaymentOverdue__c=true AND Customer_Pay_Plan_Header__c != null AND Customer_Pay_Plan_Header__r.Customer__c != null AND Customer_Pay_Plan_Header__r.Customer__r.Status__C = \'Active\' AND marked_for_interest__c = false';
                                  
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext info, List<Standard_Customer_Pay_Plan_Detail__c> scppdList){
       if(scppdList.size() > 0){
            InterestManagementServices.markForInterestCalculation(scppdList);
       }
    }
    
    global void finish(Database.BatchableContext info){     
    }   
    
    global void execute(SchedulableContext sc) {
      MarkForInterestBatch b = new MarkForInterestBatch (); 
      database.executebatch(b,10);
     }    
}