src/objects/Customer_Pay_Plan_Header__c.object
<CustomObject>
    <fields>
        <fullName>Effect_To_Date__c</fullName>
        <label>Effect To Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tower</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Tower__c.ProjectName__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Customer Pay Plan Headers</relationshipLabel>
        <relationshipName>Customer_Pay_Plan_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Pay Plan Header</label>
    <nameField>
        <displayFormat>CPPH-{000}</displayFormat>
        <label>Customer Pay Plan Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pay Plan Headers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Days_to_Send_Demand__c</fullName>
        <label>Days to Send Demand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectName</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Construction_Stages__c.object
<CustomObject>
    <fields>
        <fullName>Actual_date_of_completion__c</fullName>
        <label>Actual date of completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_date_of_completion__c</fullName>
        <label>Planned date of completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Construction_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup the tower that this particular construction stage belongs to</description>
        <label>Tower</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Tower__c.ProjectName__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Tower__c</referenceTo>
        <relationshipName>Project_Construction_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Construction Schedule</label>
    <nameField>
        <label>Project Construction Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Construction Stages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Area_value__c</fullName>
        <label>Actual Area value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Unit_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit_Type__c.RDS_Project__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit_Type__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TowerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TowerName</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Project_Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Status__c</fullName>
        <label>Unit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Returned To Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Welcome Call Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP - RM Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refuge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possession Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Unit_Type__c.object
<CustomObject>
    <label>Project Unit Type</label>
    <nameField>
        <label>Project Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Unit Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Standard_Customer_Pay_Plan_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Stage_Update_Date__c</fullName>
        <label>Construction Stage Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Pay_Plan_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Pay Plan Header</label>
        <referenceTo>Customer_Pay_Plan_Header__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Months_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Day/Months Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Months__c</fullName>
        <label>Days/Months</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>Date on which the demand should be raised for this milestone. Automatically managed by the system based on the  Construction Stages</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Milestone_Achieved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the construction stage is complete</description>
        <label>Is Milestone Achieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Construction_Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Construction Stages</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Construction_Stages__c.Tower__c</field>
                <operation>equals</operation>
                <valueField>$Source.Tower__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Construction_Stages__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Standard Customer Pay Plan Details</relationshipLabel>
        <relationshipName>Standard_Customer_Pay_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Customer Pay Plan Detail</label>
    <nameField>
        <displayFormat>SCPPD-{000}</displayFormat>
        <label>Standard Customer Pay Plan Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Customer Pay Plan Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateConsStageNew.cls
public with sharing class UpdateConsStageNew {
	public Id projectId {
		get;
		set;
	}
	public Project__c p {
		get;
		set;
	}
	public Id towerId {
		get;
		set;
	}
	public Id stageId {
		get;
		set;
	}
	public Date dueDate {
		get;
		set;
	}
	public Date plannedDate {
		get;
		set;
	} public String updateType {
		get;
		set;
	}
	
	public attachment objattachment {
		get {
			if (objattachment == null) objattachment = new attachment();
			return objattachment;
		}
		set;
	}
	// constructor to intialize the project id based on the URL parameter
	public UpdateConsStageNew() {
		ProjectID = Apexpages.currentPage().getParameters().get('Pid');
		towerId = null;
		stageId = null;
		dueDate = null;
		plannedDate = null;
		updateType = ''; 
		if (ProjectID != null) {
			List < Project__c > lstProj = [select id, Name, Days_To_Send_Demand__c from Project__c where id = : ProjectID];
			if (lstProj.size() > 0) {
				p = lstProj[0];
			}
		}
	}
	// list of towers in this project
	public List < SelectOption > getTowerSelectList() {
		List < SelectOption > options = new List < Selectoption > ();
		List < Tower__c > qResult = new List < Tower__c > ([Select Id, Name from Tower__c where ProjectName__c = : projectID order by Name]);
		options.add(new SelectOption('', 'Select a Tower'));
		for (Tower__c t: qResult) {
			options.add(new SelectOption(t.Id, t.Name));
		}
		return options;
	}

	// getting the list of construction stage related to the chosen tower
	public List < SelectOption > getConstructionSelectList() {
		List < Project_Construction_Stages__c > lstPConStg = [Select p.Id, p.Name from Project_Construction_Stages__c p
		where p.Project__c = : ProjectID and tower__c = : towerId and tower__c != null];
		List < SelectOption > options = new List < SelectOption > ();
		if (lstPConStg.size() > 0) {
			options.add(new SelectOption('', 'Select a Stage'));
			for (Project_Construction_Stages__c PConStg: lstPConStg) {
				options.add(new SelectOption(PConStg.id, PConStg.Name));
			}
		}
		return options;
	}

	public list<SelectOption> updateOptions
    {
        get
        {
        	list<SelectOption> searchOptions = new list<SelectOption>();
           	searchOptions.add(new SelectOption('plannedDate', 'Planned Date'));
           	searchOptions.add(new SelectOption('completionDate', 'Completion Date'));
            return searchOptions;
        }
        set;
    }
	// save method: updates the due date the project construction stage record, upload the arch certificate
	// as an attachment, updates the customer pay plan records associated with this construction stage mile stone.
	public pageReference save() {
		System.debug('Due Date:' + dueDate);
		System.debug('Planned Date:' + plannedDate);
		System.debug('update type:' + updateType);
		// planned Date logic
		if(String.isBlank(updateType)) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'Please select a date to update'));
			return null;
		}
		if(updateType.equals('plannedDate') &&  plannedDate == null) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'Please select a planned date'));
			return null;
		} else if(updateType.equals('plannedDate') &&  plannedDate != null){ // update the planned completionDate	
			try {
				Project_Construction_Stages__c pcons = new Project_Construction_Stages__c(id = stageId, Planned_date_of_completion__c = plannedDate);
				upsert pcons;
				System.debug('Due Date before calling update:' + DueDate);
				UpdCustPayPlanDueDatesforSoldUnits(plannedDate);
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Planned Date Updated'));
			} catch (Exception e) {
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'error updating stage:' + e.getMessage()));
			} finally {
				stageId = null;
				towerId = null;
				dueDate = null;
				plannedDate = null;
				updateType = '';
				objattachment = null;
				return null;
			}
		} else if (updateType.equals('completionDate') && dueDate == null) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'Please select an actual completion date'));
			return null;
		} else if ( dueDate != null && (objattachment.name == null || objattachment.name == '')) {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Architect certificate upload is mandatory for milestone completion'));
			return null;
		} else if(duedate != null){ //update the actual completion date
			try {
				upload();
				Project_Construction_Stages__c pcons = new Project_Construction_Stages__c(id = stageId, Actual_date_of_completion__c = dueDate);
				upsert pcons;
				System.debug('Due Date before calling update:' + DueDate);
				UpdCustPayPlanDueDatesforSoldUnits(dueDate);
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Completion Date Updated'));
			} catch (Exception e) {
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'error updating stage:' + e.getMessage()));

			} finally {
				stageId = null;
				towerId = null;
				dueDate = null;
				plannedDate = null;
				updateType = '';
				objattachment = null;
				return null;
			}
			
		} else {
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error Occurred, due to incorrect data entered'));
		}
		return null;
	}

	// takes the user back to the project detail page
	public PageReference cancel() {
		PageReference pv = new PageReference('/' + p.Id);
		return pv;
	}

	// just a method for action function to call and then rerender the output panels
	// facing some issues with rerender, required input and page specific validations
	public void dummy() {
	}
	
	public PageReference refresh() {
		PageReference pRef = Apexpages.currentPage();
		pRef.setredirect(true);
		return pRef;
	}
	// method for uploading the architect certificate
	public boolean upload() {
		objattachment.OwnerId = UserInfo.getUserId();
		objattachment.IsPrivate = true;
		objattachment.ParentId = stageId;
		if (objattachment.ParentId != null) {
			insert objattachment;
			return true;
		}
		return false;
	}

	// method for updating the existing customer payplan records that
	// are linked to this specific milestone.
	public PageReference UpdCustPayPlanDueDatesforSoldUnits(Date d) {
		System.debug('Date received:' + d);
		List < Project_Unit__c > lstProjectUnit = new List < Project_Unit__c > ();
		List < Standard_Customer_Pay_Plan_Detail__c > lstStdCusPayPlandtl = new List < Standard_Customer_Pay_Plan_Detail__c > ();
		Set<ID> stageIDSet = new Set<ID>();
		string QueryforUnit = null;
		QueryforUnit = 'Select id,Project_Unit_Type__c, Actual_Area_value__c from Project_Unit__c where ';

		QueryforUnit = QueryforUnit + ' createddate != null AND Project__c = \'' + p.Id + '\' AND Unit_Status__c=\'Sold\' AND TowerName__c = \'' + towerID + '\'';

		lstprojectunit = Database.query(QueryforUnit);

		System.debug('Unit List to update:' + lstProjectUnit);
		if (lstprojectunit.size() > 0) {
			lstStdCusPayPlandtl = [SELECT s.Id, s.Days_Months__c, s.Days_Months_Value__c, Due_Date__c , Is_Milestone_Achieved__c, Construction_Stage_Update_Date__c
									FROM Standard_Customer_Pay_Plan_Detail__c s 
									WHERE s.Customer_Pay_Plan_Header__r.Project__c = : p.ID 
									AND s.Customer_Pay_Plan_Header__r.Effect_To_Date__c = : null AND 
									s.Project_Construction_Stages__c = : stageID AND 
									s.Customer_Pay_Plan_Header__r.Project_Unit__c IN: lstprojectunit];
									
			List < Standard_Customer_Pay_Plan_Detail__c > lstSCPPD = new List < Standard_Customer_Pay_Plan_Detail__c > ();
			if (lstStdCusPayPlandtl.size() > 0) {
				for (Standard_Customer_Pay_Plan_Detail__c objSCPPD: lstStdCusPayPlandtl) {

					System.debug('Here is the list to update' + objSCPPD);
					string DayMonth = objSCPPD.Days_Months__c;
					decimal DayMonthValue = objSCPPD.Days_Months_Value__c;

					if (DayMonthValue == null) {
						DayMonthValue = 0;
					}

					if (DayMonth == 'Day(s)') {
						objSCPPD.Construction_Stage_Update_Date__c = d.addDays(DayMonthValue.intvalue());
						objSCPPD.Due_Date__c = d.addDays(DayMonthValue.intvalue());
					} else {
						objSCPPD.Construction_Stage_Update_Date__c = d.addMonths(DayMonthValue.intvalue());
						objSCPPD.Due_Date__c = d.addMonths(DayMonthValue.intvalue());
					}
					if(updateType.equals('completionDate')) {
						objSCPPD.Is_Milestone_Achieved__c = true;
					}
					lstSCPPD.add(objSCPPD);
					
				}
			}
			if (lstSCPPD.size() > 0) {
				update lstSCPPD;
			} 
		}
		return null;
	}
}