src/objects/Interest_Details__c.object
<CustomObject>
    <description>Stores information to calculate interest so far on any account.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Aging_System__c</fullName>
        <formula>if(
      OR (isnull(End_Date__c), isblank(End_Date__c)), 
       TODAY() - Start_Date__c, 
       End_Date__c - Start_Date__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aging (System)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Corrected_Age__c</fullName>
        <label>Corrected Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Installment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Customer Pay Plan Detail</label>
        <referenceTo>Standard_Customer_Pay_Plan_Detail__c</referenceTo>
        <relationshipLabel>Interest Details</relationshipLabel>
        <relationshipName>Interest_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Interest Details</relationshipLabel>
        <relationshipName>Interest_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Service Tax Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interest Detail</label>
    <nameField>
        <displayFormat>Id-{000000000}</displayFormat>
        <label>Interest Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>RDS_Interest_Rate__c</fullName>
        <label>Interest Rate %</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalculateInterestBatch.cls
global class CalculateInterestBatch implements Database.Batchable <sObject>, Schedulable 
{
     Public String Query;
    
    public CalculateInterestBatch() 
    {
     Query = 'Select Id, Name, Installment_Amount__c, Service_Tax_Amount__c, Milestone__c, project__r.RDS_Interest_Rate__c,Aging_System__c, Corrected_Age__c from Interest_Details__c where active__C = true';
                                  
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext info, List<Interest_Details__c> IDList){
       if(IDList.size() > 0){
            InterestManagementServices.calculateInterest(IDList);
       }
    }
    
    global void finish(Database.BatchableContext info){     
    }   
    
    global void execute(SchedulableContext sc) {
      CalculateInterestBatch b = new CalculateInterestBatch(); 
      database.executebatch(b,10);
     }    
}