src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_R__c</fullName>
        <label>City</label>
        <picklist>
            <controllingField>Residential_State_Province__c</controllingField>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Blair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amalapuram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anakapalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bapatla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bheemunipatnam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhimavaram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bobbili</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chilakaluripet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuddapah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharmavaram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eluru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gooty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudivada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guntakal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guntur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hanamkonda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hindupur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaggaiahpet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jammalamadugu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kadapa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kadiri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kakinada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandukur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kavali</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IP_Address_Web2Lead__c</fullName>
        <label>IP Address Web2Lead</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Sub_Source__c</fullName>
        <label>Lead Sub Source</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>99 acres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magic Bricks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Different Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Times of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sakal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maharashtra Times</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lokmat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loksatta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Times</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Mirchi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fever 104</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akurdi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alandi Devachi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alandi Khed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alandi Road</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambegaon BK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anandnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armament</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aundh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aundh Road</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balaji Nagar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Budget__c</fullName>
        <label>Budget Range</label>
        <picklist>
            <picklistValues>
                <fullName>Below 1 Cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 to 2 Cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 to 5 Cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Cr &amp; above</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Country_Code__c</fullName>
        <label>Country Code</label>
        <picklist>
            <controllingField>RDS_Country__c</controllingField>
            <picklistValues>
                <fullName>+61</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+852</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+86</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+91</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>+971</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+93</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+355</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+213</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-684</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+376</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+244</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-264</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+672</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-268</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+374</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+297</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+43</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-242</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+973</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+880</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-246</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+375</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+501</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+229</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+1-441</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>+975</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sweden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zeland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RDS_Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email RDS</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RDS_Mobile__c</fullName>
        <externalId>true</externalId>
        <label>Mobile RDS</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RDS_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Remarks__c</fullName>
        <label>Source Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Web_Banner_Source__c</fullName>
        <label>Web Banner Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WebToLeadServices.cls
global class WebToLeadServices {

    global static final String PARAM_MISSING = 'MISSING REQUIRED PARAMETERS';
    global static final String PROJECT_INVALID = 'INVALID PROJECT SELECTED';
    global static final String SOURCE_INVALID = 'INVALID SOURCE';


    global class result {
        webservice Integer returnCode;
        webservice String message;
        webservice Id recordId;
    }

    global class WebLead {
        webservice String fullName;
        webservice String emailAddress;
        webservice String country;
        webservice String city;       // added as per client's requirement
        webservice String dialingCode;
        webservice String mobileNumber;
        webservice String projectInterested;
        webservice String budget;
        webservice String CampaignCode;
        webservice String source; //click2call, microsite, corpsite, liveserv etc.
        webservice String webbannerSource;
        webservice String UTMCampaign;
        webservice String UTMDisplay;
        webservice String UTMMedium;
        webservice String UTMSource;
        webservice String UTMTerm;
        webservice String IPAddress;
    }

    webservice static result createLeadFromWeb(WebLead wl) {
        List < Lead > leadList = new List < Lead > ();
        Lead l = null;
        result r = new result();
        String projectId = null;
        System.debug('WEB LEAD:' + wl);
        if (String.isNotBlank(wl.source) && wl.source.equals('DIGITAL MARKETING')) {
           if (String.isBlank(wl.fullName) || String.isBlank(wl.mobileNumber) || String.isBlank(wl.emailAddress) || String.isBlank(wl.dialingCode) || String.isBlank(wl.source) || String.isBlank(wl.city)) {
                System.debug('Missing Required Parameters');
                r.returnCode = 1;
                r.message = PARAM_MISSING;
                r.recordId = null;
                return r;
            } else {
                List < Project__c > pList = [Select Id, Name from project__c where Name = : wl.projectInterested];
                if (pList.size() == 1) {
                    projectId = pList[0].Id;
                } else {
                    System.debug('Project Error:' + pList);
                    r.returnCode = 1;
                    r.message = PROJECT_INVALID;
                    r.recordId = null;
                    return r;
                }
                l = new Lead(
                lastName = wl.fullName,
                RDS_Mobile__c = wl.mobileNumber,
                RDS_Email__c = wl.emailAddress,
                MobilePhone = wl.mobileNumber,
                Email = wl.emailAddress,
                leadsource = 'Presales',
                Lead_Sub_Source__c = 'Web',
                RDS_Country__c = wl.country,
                City_R__c = wl.city,
                RDS_Country_Code__c = wl.dialingCode,
                RDS_Budget__c = wl.budget,
                RDS_Project__c = projectId,
                Source_Remarks__c = wl.source,
                Campaign_Code__c = wl.CampaignCode,
               web_banner_source__c = wl.webBannerSource,
                IP_address_web2lead__c = wl.IPAddress,
          
        /////////////////////////--------------- vikas added below field on dated 23-08-16 -----------------------------/////////////////////
                UTM_Campaign__c = wl.UTMCampaign,
                UTM_Display__c = wl.UTMDisplay,
                UTM_Medium__c = wl.UTMMedium,
                UTM_Source__c = wl.UTMSource,
                UTM_Term__c = wl.UTMTerm);
        /////////////////--------------------- vikas added end here -------------------------------///////////////////////////////
            }
        } else {
            System.debug('Invalid Source:' + wl.source);
            r.returnCode = 1;
            r.message = SOURCE_INVALID;
            r.recordId = null;
            return r;
        }
        if (l != null) {
            leadList.add(l);
            try {
                List < DupResultsDTO > dupList = LeadManagementServices.leadPreprocessing(leadList, 'WEB');
                if (dupList.isEmpty()) {
                    try {
                        Database.saveResult[] srList = Database.insert(leadList, true);
                        for (Database.SaveResult sr: srList) {
                            if (sr.isSuccess()) {
                                // Operation was successful, so get the ID of the record that was processed
                                System.debug('Successfully inserted lead. lead ID: ' + sr.getId());
                                r.recordId = sr.getId();
                                r.returnCode = 0;
                                r.message = 'SUCCESS';
                                try {
                                    // once the lead is created, save the entire enquiry information as a task of type enquiry received.
                                    // this is so that the complete form info is saved somewhere
                                    Map < Id, Lead > enquiryMap = new Map < Id, Lead > ();
                                    enquiryMap.put(sr.getId(), l);
                                    Map < Id, Task > whoIdMap = new Map < Id, Task > ();
                                    whoIdMap = TaskManagementServices.createTaskforEnquiries(enquiryMap);
                                } catch (Exception ex) {
                                    System.debug('Catch and Ignore enquiry task create exception:' + ex.getMessage());
                                }
                            } else {
                                // Operation failed, so get all errors  
                                String msg = null;
                                for (Database.Error err: sr.getErrors()) {
                                    msg = 'Lead Insert Failed :' + err.getMessage();
                                }
                                r.returnCode = 1;
                                r.message = msg;
                                r.recordId = null;
                                return r;
                            }
                        }
                    } catch (System.DmlException ex) {
                        String msg = null;
                        for (Integer i = 0; i < ex.getNumDml(); i++) {
                            msg = 'Lead Insert Failed :' + ex.getMessage();
                        }
                        r.returnCode = 1;
                        r.message = msg;
                        r.recordId = null;
                        return r;
                    }
                } else {
                    r.recordId = dupList[0].duplicateMaster;
                    r.returnCode = 0;
                    r.message = 'SUCCESS';
                }
            } catch (GlobalException g) {
                r.returnCode = 1;
                r.message = g.getErrorMsg()[0];
                r.recordId = null;
                return r;
            }
            return r;
        } else {
            System.debug('Lead list empty:');
            r.returnCode = 1;
            r.message =  'UNKNOWN EXCEPTION';
            r.recordId = null;
            return r;
        }
    }
}