src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Applicants_Name__c</fullName>
        <label>Other Applicants Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Name__c</fullName>
        <label>Primary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Project field is blank or Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Project_Unit__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Units</relationshipLabel>
        <relationshipName>Project_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Unit</label>
    <nameField>
        <label>Project Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project_Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Receipt__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Rs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount (Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Drawee Bank</label>
        <referenceTo>Bank__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cheque_DD_Amount_Rs__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cheque_DD_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_DD__c</fullName>
        <label>Cheque/DD No.</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>Indian Rupee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK Pound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubai Dirham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kuwaiti Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saudi Riyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese Yen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese Yuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong Dollar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>European Euro</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DraweeBank__c</fullName>
        <label>Drawee Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Abhyudaya Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad Mercantile Co-Op Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Janata Commercial Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akola Urban Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allahabad Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andaman and Nicobar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh Mahesh Co-Op Urban Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andhra Pradesh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arunachal Pradesh State Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assam Co-operative Apex Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axis Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Baroda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Maharashtra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bassein Catholic Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharat Co-operative Bank (Mumbai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bharati Sahakari Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihar State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bombay Mercantile Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canara Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catholic Syrian Bank Ltd.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank of India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh State Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhattisgarh Rajya Sahakari Bank Maryadit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citizen Credit Co-operative Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmos Co-operative Urban Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Drawn_in_favour_of__c</fullName>
        <label>Drawn in favour of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Instrument</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD/Pay Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Project__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAN_no_of_TDS_Deductor__c</fullName>
        <label>PAN no of TDS Deductor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physically_Cheque_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physically Cheque Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Unit__c.Unit_Status__c</field>
                <operation>equals</operation>
                <value>Block, CRM Returned To Sales, Hold, Sold, Vacant, Welcome Call Pending, BIP - Sales, BIP - RM Verification, BIP - CRM, BIP</value>
            </filterItems>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Project_Unit__c.Project__c</valueField>
            </filterItems>
            <infoMessage>Block, CRM Returned To Sales, Vacant, Welcome Call Pending, BIP - Sales, BIP - RM Verification, Sold, Block</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Unit__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason for cheque rejection</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Receipt_Number__c</fullName>
        <formula>(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.TowerName__r.Name ,2) &amp; &apos;-&apos; &amp;  Project_Unit__r.Name &amp; &apos;/&apos; &amp;  TEXT(Receipt_Date__c)  &amp; &apos;/&apos; &amp;  Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Receipt Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/S_ChequeReceiving.cls
public class S_ChequeReceiving {
     public List < rMainWrapper > rwList {
      get;
      set;
     }
     public List < Receipt__C > lstReceipt {
      get;
      set;
     }
     public Boolean error {
      get;
      set;
     }
     public S_ChequeReceiving() {
        error = false;
        getlist();
     }
     public PaginationController.PaginationWrapper pgw;
     public Transient List<Receipt__c> objR {get;set;}
     public Transient List<Receipt__c> dummyList {get;set;}
     

     public void getlist() {
     
        objR = new List<Receipt__c>();
        pgw = new PaginationController.PaginationWrapper();
        pgw.list_size = 100;
        pgw.counter = 0;
        pgw.created_date = '';
        dummyList = new List<Receipt__c>();
        
        
         rwList = new List<rMainWrapper>();
            lstReceipt = new list < Receipt__c > ([select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC limit:pgw.list_size offset:pgw.counter]);
           
           
       dummyList = [select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC];                     
          
                       
           if(dummyList.size() > 0){
                pgw.total_size = dummyList.size();    
                pgw.last_date =  dummyList[dummyList.size() - 1].name;            
           }
         
               
           
          if (lstReceipt.size() > 0) {
               for (Receipt__c r: lstReceipt) {
                   if (String.isNotBlank(r.Receipt_Status__c) && r.Receipt_Status__c.equalsIgnoreCase('UnProcessed') && !r.Physically_Cheque_Received__c) {
                        r.Receipt_Status__c = 'UnProcessed';
                    } 
                    String applicantNames;
                    if(String.isNotBlank(r.Opportunity__r.Primary_Name__c)) 
                        applicantNames = r.Opportunity__r.Primary_Name__c;
                    if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c) && string.IsnotBlank(applicantNames))
                        applicantNames += ',' + r.Opportunity__r.Other_Applicants_Name__c;
                    else if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c))
                        applicantNames = r.Opportunity__r.Other_Applicants_Name__c;
                    rMainWrapper rw = new rMainWrapper(r, applicantNames);
                    rwList.add(rw);
                }
          }
     }

     public void Save() {
            error = false;
            
          for (rMainWrapper rw: rwList) {
                rw.style0='';
                rw.style1='';
                rw.style2='';
                System.debug('RECEIPT DATA:' + rw);
                // throw an error if physical verification is checked but the status of verification is blank
               if (rw.rCloned.Physically_Cheque_Received__c == true && 
                    String.isnotBlank(rw.r.Receipt_status__c) && 
                    rw.r.Receipt_status__c.equalsIgnoreCase('UnProcessed') && 
                    String.isBlank(rw.rCloned.Reason_for_rejection_new__c)
                ) {
                    rw.style0 = 'error';
                    error = true;
                    // throw an error if Foreign Curreny payment is accepted but forex amt is not filled
               } else if (rw.rCloned.Physically_Cheque_Received__c == true && 
                    String.isnotBlank(rw.r.Receipt_status__c) && 
                    rw.r.Receipt_status__c.equalsIgnoreCase('Processed-Sent for Banking') && 
                    String.isNotBlank(rw.rCloned.Banking__c) &&
                    rw.rCloned.Banking__c.equalsIgnoreCase('Payment Successful') && 
                    String.isNotBlank(rw.r.Currency__c) &&
                    !(rw.r.Currency__c.equalsIgnoreCase('Indian Rupee') || rw.r.Currency__c.equalsIgnoreCase('RUPEES')) &&
                    rw.rCloned.Forex__c == null
                ) {
                    rw.style2 = 'error';
                    error = true;
               }
          }
          System.debug('out of loop1');
          List<Receipt__c> updateReceiptList = new List<Receipt__c>();
          List<Task> lstTask = new List<Task>();
          if (error) {
            System.debug('In error');
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please correct the errors below'));
            return;
          }else{
              for (rMainWrapper rw: rwList) {
                rw.style0='';
                rw.style1='';
                rw.style2='';
                // physical verification is accepted or rejected, store the status in the receipt
                System.debug('List of receipts for processing:' + rw);
                if (rw.rCloned.Physically_Cheque_Received__c == true && 
                String.isNotBlank(rw.r.Receipt_status__c) && 
                rw.r.Receipt_status__c.equalsIgnoreCase('UnProcessed') && 
                String.isNotBlank(rw.rCloned.Reason_for_rejection_new__c)
                ) {
                    
                    if (rw.rCloned.Reason_for_rejection_new__c.equalsIgnoreCase('Accepted')) {
                        rw.r.Receipt_status__c = 'Processed-Sent for Banking';
                        rw.r.Physically_Cheque_Received__c = true;
                        rw.r.Reason_for_rejection_new__c = rw.rCloned.Reason_for_rejection_new__c;
                    } else {
                        rw.r.Receipt_status__c = 'Physical Verification Rejected';
                        rw.r.Physically_Cheque_Received__c = true;
                        rw.r.Reason_for_rejection_new__c = rw.rCloned.Reason_for_rejection_new__c;
                        Task objTask = new Task();
                        objTask.Subject = rw.r.Cheque_DD__c + ' ' + 'is rejected by Finance Team for ' + rw.r.Reason_for_rejection_new__c;
                        objTask.WhatId = rw.r.Id;
                        objTask.OwnerId = rw.r.OwnerId;
                        objTask.Description = rw.r.Reason__c;
                        lstTask.add(objTask);
                    }
                    rw.r.status_change_date__c = system.today();
                    updateReceiptList.add(rw.r);
                    // if banking is completed, store the payment received /rejected status
               } else if (rw.rCloned.Physically_Cheque_Received__c == true && 
                    String.isnotBlank(rw.r.Receipt_status__c) && 
                    rw.r.Receipt_status__c.equalsIgnoreCase('Processed-Sent for Banking') && 
                    String.isNotBlank(rw.rCloned.Banking__c)
                ) {
                    if (rw.rCloned.Banking__c.equalsIgnoreCase('Payment Successful')) {
                     rw.r.Receipt_status__c = 'Cleared';
                     rw.r.Banking__c = rw.rCloned.Banking__c;
                     if(rw.rCloned.Forex__c != null && !(rw.r.Currency__c.equalsIgnoreCase('Indian Rupee') || rw.r.Currency__c.equalsIgnoreCase('RUPEES'))) {
                        rw.r.Forex__c = rw.rCloned.Forex__c;
                        rw.r.Amount_Rs__c = rw.r.Forex__c;
                        rw.r.Currency__c = 'Indian Rupee';
                        rw.r.Total_Amount__c = rw.r.Forex__c;
                        rw.r.On_Account_Money__c = rw.r.Forex__c;
                     }
                    } else {
                        System.debug('Inside Dishonored loop:' + rw);
                     rw.r.Receipt_status__c = 'Dishonored';
                     rw.r.Banking__c = rw.rCloned.Banking__c;
                     Task objTask = new Task();
                     objTask.Subject = rw.r.Cheque_DD__c + ' ' + 'is rejected by Finance Team for ' + rw.r.Banking__c;
                     objTask.WhatId = rw.r.Id;
                     objTask.OwnerId = rw.r.OwnerId;
                     objTask.Description = rw.r.Reason__c;
                     lstTask.add(objTask);
                    }
                    rw.r.status_change_date__c = system.today();
                    updateReceiptList.add(rw.r);
                }
              }
          }
          if(updateReceiptList.size() > 0){
            System.debug('In Update:' + updateReceiptList);
            update updateReceiptList;
          }
          if(lstTask.size() > 0) {
            System.debug('In Task creation:');
            insert lstTask;
          }
     getlist();
     return;
    }

    public pagereference Back() {
        return new pagereference('/home/home.jsp');
    }
    
    public class rMainWrapper {
         public Receipt__c r {
          get;
          set;
         }
         public Receipt__c rCloned {
          get;
          set;
         }
         public String style0 {
          get;
          set;
         }
         public String applicantNames {
          get;
          set;
         }
         public String style1 {
          get;
          set;
         }
         public String style2 {
          get;
          set;
         }
         
         public rMainWrapper(Receipt__c r, String applicantNames) {
          this.r = r;
          this.applicantNames = applicantNames;
          this.rCloned = new Receipt__c();
          this.rCloned.Physically_Cheque_Received__c = r.Physically_Cheque_Received__c;
          if(r.Banking__c != null)
            this.rCloned.Banking__c = r.Banking__c;
          
          if(r.Reason_for_rejection_new__c != null)
             this.rCloned.Reason_for_rejection_new__c = r.Reason_for_rejection_new__c;
          
          if(r.Forex__c != null)
            this.rCloned.Forex__c = r.Forex__c;
          
          this.style0 = '';
          this.style1 = '';
          this.style2 = '';
         }
    }
    
    public Boolean getDisablePrevious() { //this will disable the previous and beginning buttons
         // system.debug('PGW:' + pgw);
         // system.debug('in previous:: '+PaginationController.DisableNext(pgw));
       return(PaginationController.DisablePrevious(pgw));
      
       
    }
    public Boolean getDisableNext() { //this will disable the next and end buttons
      //system.debug('PGW:' + pgw);
      //system.debug('in next:: '+PaginationController.DisableNext(pgw));
       return(PaginationController.DisableNext(pgw));
    }
    
     public PageReference Beginning() { //user clicked beginning
        pgw= PaginationController.Beginning(pgw);
        
        //objR = new List<Receipt__c>();
       
        //wrapperscppdList = new List<wrapperclass>();
        
         rwList = new List<rMainWrapper>();
            lstReceipt = new list < Receipt__c > ([select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC limit:pgw.list_size offset:pgw.counter]);
          if (lstReceipt.size() > 0) {
               for (Receipt__c r: lstReceipt) {
                   if (String.isNotBlank(r.Receipt_Status__c) && r.Receipt_Status__c.equalsIgnoreCase('UnProcessed') && !r.Physically_Cheque_Received__c) {
                        r.Receipt_Status__c = 'UnProcessed';
                    } 
                    String applicantNames;
                    if(String.isNotBlank(r.Opportunity__r.Primary_Name__c)) 
                        applicantNames = r.Opportunity__r.Primary_Name__c;
                    if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c) && string.IsnotBlank(applicantNames))
                        applicantNames += ',' + r.Opportunity__r.Other_Applicants_Name__c;
                    else if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c))
                        applicantNames = r.Opportunity__r.Other_Applicants_Name__c;
                    rMainWrapper rw = new rMainWrapper(r, applicantNames);
                    rwList.add(rw);
                }
          }
         
         
        return null;
     }   
     
     public PageReference Previous() { //user clicked previous button
       pgw = PaginationController.Previous(pgw);
       
       //objR = new List<Receipt__c>();
         
      // wrapperscppdList = new List<wrapperclass>();
         
         rwList = new List<rMainWrapper>();
            lstReceipt = new list < Receipt__c > ([select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC limit:pgw.list_size offset:pgw.counter]);
          if (lstReceipt.size() > 0) {
               for (Receipt__c r: lstReceipt) {
                   if (String.isNotBlank(r.Receipt_Status__c) && r.Receipt_Status__c.equalsIgnoreCase('UnProcessed') && !r.Physically_Cheque_Received__c) {
                        r.Receipt_Status__c = 'UnProcessed';
                    } 
                    String applicantNames;
                    if(String.isNotBlank(r.Opportunity__r.Primary_Name__c)) 
                        applicantNames = r.Opportunity__r.Primary_Name__c;
                    if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c) && string.IsnotBlank(applicantNames))
                        applicantNames += ',' + r.Opportunity__r.Other_Applicants_Name__c;
                    else if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c))
                        applicantNames = r.Opportunity__r.Other_Applicants_Name__c;
                    rMainWrapper rw = new rMainWrapper(r, applicantNames);
                    rwList.add(rw);
                }
          }
         
         return null;
     }   
     
     public PageReference Next() { //user clicked next button
        pgw = PaginationController.Next(pgw);
        
        //objR = new List<Receipt__c>();
        
       // wrapperscppdList = new List<wrapperclass>();
       
               rwList = new List<rMainWrapper>();
            lstReceipt = new list < Receipt__c > ([select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC limit:pgw.list_size offset:pgw.counter]);
          if (lstReceipt.size() > 0) {
               for (Receipt__c r: lstReceipt) {
                   if (String.isNotBlank(r.Receipt_Status__c) && r.Receipt_Status__c.equalsIgnoreCase('UnProcessed') && !r.Physically_Cheque_Received__c) {
                        r.Receipt_Status__c = 'UnProcessed';
                    } 
                    String applicantNames;
                    if(String.isNotBlank(r.Opportunity__r.Primary_Name__c)) 
                        applicantNames = r.Opportunity__r.Primary_Name__c;
                    if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c) && string.IsnotBlank(applicantNames))
                        applicantNames += ',' + r.Opportunity__r.Other_Applicants_Name__c;
                    else if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c))
                        applicantNames = r.Opportunity__r.Other_Applicants_Name__c;
                    rMainWrapper rw = new rMainWrapper(r, applicantNames);
                    rwList.add(rw);
                }
          }
         
        return null;
     }  
     
     public PageReference End() { //user clicked end
        pgw = PaginationController.End(pgw);
        
        //objR = new List<Receipt__c>();
         
        //wrapperscppdList = new List<wrapperclass>();
         //system.debug('last anem:: '+pgw.last_date);
         //system.debug('limit is::'+pgw.last_limit);
         
        rwList = new List<rMainWrapper>();
            lstReceipt = new list < Receipt__c > ([select Receipt_Number__c, id, OwnerId, Physically_Cheque_Received__c, Total_Amount__c, 
            Cheque_DD__c, Cheque_DD_Date__c, Mode__c,Drawn_in_favour_of__c,
           Bank__r.name, Cheque_DD_Amount_Rs__c, Project_Unit__c, Project_Unit__r.Project__r.name, Currency__c,PAN_no_of_TDS_Deductor__c,
           Project_Unit__r.name, Opportunity__c, Reason__c, Opportunity__r.name, 
           Opportunity__r.Primary_Name__c,Opportunity__r.Other_Applicants_Name__c,
           name, Amount_Rs__c, DraweeBank__c, Reason_for_rejection_new__c, Receipt_Status__c, Banking__c, FOREX__c
           from Receipt__c
           where Receipt_Status__c NOT IN('Dishonored', 'Cleared', 'Physical Verification Rejected')
           Order By CreatedDate DESC limit:pgw.list_size offset:pgw.counter]);
          if (lstReceipt.size() > 0) {
               for (Receipt__c r: lstReceipt) {
                   if (String.isNotBlank(r.Receipt_Status__c) && r.Receipt_Status__c.equalsIgnoreCase('UnProcessed') && !r.Physically_Cheque_Received__c) {
                        r.Receipt_Status__c = 'UnProcessed';
                    } 
                    String applicantNames;
                    if(String.isNotBlank(r.Opportunity__r.Primary_Name__c)) 
                        applicantNames = r.Opportunity__r.Primary_Name__c;
                    if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c) && string.IsnotBlank(applicantNames))
                        applicantNames += ',' + r.Opportunity__r.Other_Applicants_Name__c;
                    else if(String.isNotBlank(r.Opportunity__r.Other_Applicants_Name__c))
                        applicantNames = r.Opportunity__r.Other_Applicants_Name__c;
                    rMainWrapper rw = new rMainWrapper(r, applicantNames);
                    rwList.add(rw);
                }
          }
        
        return null;
     }
      public Integer getTotal_size() {
        return (PaginationController.getTotal_size(pgw));
    }
    
    
    public Integer getPageNumber() {
         return (PaginationController.getPageNumber(pgw));
    }
    
      public Integer getTotalPages() {
    return (PaginationController.getTotalPages(pgw));
    }
}