src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Code__c</fullName>
        <externalId>true</externalId>
        <label>Project Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zapier_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Sub_Source__c</fullName>
        <label>Lead Sub Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MobileNo__c</fullName>
        <label>MobileNo</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Zapier Leads</relationshipLabel>
        <relationshipName>Zapier_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zapier Lead</label>
    <nameField>
        <label>Zapier Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zapier Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTrgZapLeads.cls
@isTest
private Class TestTrgZapLeads {
@isTest
Static void Test1(){
        Project__c p =new Project__c();
        p.Name = 'Project';
        p.Project_Code__c = 'Project123';
        Insert p;
    
        Zapier_Lead__c  z = new Zapier_Lead__c();
        z.email__c = 'click2call@email.com';
        z.Name = 'click2call';
        z.MobileNo__c = '9080706050';
        z.Lead_Source__c = 'DIGITAL';
        z.Lead_Sub_Source__c = 'Facebook';
        z.Campaign_Code__c = '2001';
        z.Project__c = p.Id;
        z.ownerid ='0050K000008X1PV';
    insert z;
    }
}