src/objects/Welcome_Call_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verify__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verify</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Call_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Welcome Call Header</label>
        <referenceTo>Welcome_Call_Header__c</referenceTo>
        <relationshipLabel>WelcomeCallChecklist</relationshipLabel>
        <relationshipName>WelcomeCallChecklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Welcome Call Checklist</label>
    <nameField>
        <label>Welcome Call Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WelcomeCallChecklist</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Welcome_Call_Header__c.object
<CustomObject>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Welcome Call Header</label>
    <nameField>
        <label>Welcome Call Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WelcomeCallHeaders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WelcomeCallRejectedPageController.cls
Public Class WelcomeCallRejectedPageController{
  public id WCHID {get;set;}
  public List<Welcome_Call_Checklist__c> WCCList {get;set;}
    public WelcomeCallRejectedPageController()
    {
        if(ApexPages.currentPage().getParameters().get('WCHid') != null && ApexPages.currentPage().getParameters().get('WCHid') != '')
        WCHID = ApexPages.currentPage().getParameters().get('WCHid');
        
        WCCList = [Select id,Name,Detail__c,Verify__c,Remarks__c,Welcome_Call_Header__r.Remarks__c,Welcome_Call_Header__c From Welcome_Call_Checklist__c Where Welcome_Call_Header__c =:WCHID and Verify__c =: False];
        system.debug('WCCList Size: ' + WCCList.size());
        if(WCCList.size() == 0)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,'There is no data for this call.');
            ApexPages.addMessage(myMsg);
        }
    
    }  

}